import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const temp=await mkdtemp(path.join(tmpdir(),'nexo-browser-'));
const origin='http://localhost:3101';
const server=spawn(process.execPath,['--import','tsx','apps/api/src/index.ts'],{cwd:process.cwd(),env:{...process.env,PORT:'3101',HOST:'127.0.0.1',APP_ORIGIN:origin,DATA_DIR:temp,DATABASE_URL:'',NODE_ENV:'development'},stdio:'pipe',windowsHide:true});
let output='';server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
let browser;
try{
 for(let attempt=0;attempt<120;attempt++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(server.exitCode!==null)throw new Error(output);await new Promise(r=>setTimeout(r,1000));}
 browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge',args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required']});
 const a=await browser.newContext({viewport:{width:1440,height:960},permissions:['microphone','camera']});
 const b=await browser.newContext({viewport:{width:1440,height:960},permissions:['microphone','camera']});
 a.setDefaultTimeout(20000);b.setDefaultTimeout(20000);const errors=[];
 for(const ctx of [a,b])await ctx.addInitScript(()=>{window.__audioRequests=0;window.__captures=[];window.__noMic='';window.__cancelScreen=false;
const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
navigator.mediaDevices.getUserMedia=async c=>{if(c.audio){window.__audioRequests++;if(window.__noMic)throw new DOMException('Microfone simulado indisponível',window.__noMic);}const stream=await original(c);window.__captures.push(stream);return stream;};
navigator.mediaDevices.getDisplayMedia=async()=>{if(window.__cancelScreen)throw new DOMException('Cancelado','NotAllowedError');const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d');let frame=0;const paint=()=>{ctx.fillStyle=frame++%2?'#684ac4':'#76d9b1';ctx.fillRect(0,0,640,360);ctx.fillStyle='white';ctx.font='30px sans-serif';ctx.fillText('NexoChat • tela de teste '+frame,30,100);};paint();const timer=setInterval(paint,100);const stream=canvas.captureStream(10);window.__captures.push(stream);stream.getVideoTracks()[0].addEventListener('ended',()=>clearInterval(timer));return stream;};
window.__pcs=[];const Native=window.RTCPeerConnection;window.RTCPeerConnection=class extends Native{constructor(...args){super(...args);window.__pcs.push(this);}};});
 const alice=await a.newPage(),bob=await b.newPage();for(const p of [alice,bob])p.on('pageerror',e=>errors.push(e.message));
 for(const [p,name] of [[alice,'alice'],[bob,'bobby']]){
  await p.goto(origin);await p.getByRole('button',{name:'Criar minha conta'}).click();await p.getByLabel('Nome de usuário',{exact:true}).fill(name);await p.getByLabel('Senha',{exact:true}).fill('Browser-test-password-123');await p.getByRole('button',{name:'Criar conta',exact:true}).click();await p.getByRole('button',{name:'Adicionar amigo',exact:true}).waitFor();
 }
 await alice.getByRole('button',{name:'Adicionar amigo',exact:true}).click();await alice.getByRole('dialog').getByLabel('Nome de usuário',{exact:true}).fill('bobby');await alice.getByRole('button',{name:'Enviar solicitação'}).click();
 await bob.getByRole('button',{name:/Solicitações/}).click();await bob.getByRole('button',{name:'Aceitar',exact:true}).click();await bob.getByRole('button',{name:'Todos',exact:true}).click();
 await alice.getByRole('button',{name:'Mensagem para bobby',exact:true}).click();await alice.getByRole('textbox',{name:'Mensagem',exact:true}).fill('Oi da interface!');await alice.getByRole('button',{name:'Enviar mensagem',exact:true}).click();
 await bob.locator('.conversation').filter({hasText:'alice'}).click();await bob.getByText('Oi da interface!',{exact:true}).waitFor();await bob.getByRole('textbox',{name:'Mensagem',exact:true}).fill('Mensagem recebida em tempo real.');await bob.getByRole('button',{name:'Enviar mensagem',exact:true}).click();await alice.getByText('Mensagem recebida em tempo real.',{exact:true}).waitFor();
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z4Z8AAAAASUVORK5CYII=','base64');
 alice.on('response',r=>{if(r.status()>=400)console.log('HTTP failure',r.status(),r.url());});

 console.log('0.6: áudio');
 await alice.getByRole('button',{name:'Gravar áudio',exact:false}).click();await alice.getByRole('button',{name:'Parar gravação'}).waitFor();await new Promise(r=>setTimeout(r,1400));await alice.getByRole('button',{name:'Parar gravação'}).click();await alice.getByLabel('Prévia da mensagem de voz').waitFor();assert.equal(await alice.evaluate(()=>window.__captures.every(s=>s.getTracks().every(t=>t.readyState==='ended'))),true);await alice.getByRole('button',{name:'Usar áudio'}).click();await alice.getByRole('button',{name:'Enviar mensagem',exact:true}).click();await bob.getByLabel('Mensagem de voz',{exact:true}).waitFor();await bob.getByLabel('Mensagem de voz',{exact:true}).evaluate(async el=>{await el.play();});await bob.waitForFunction(()=>document.querySelector('.message-content audio')?.currentTime>0);
 console.log('0.6: tópicos e busca');
 await alice.locator('.message').filter({hasText:'Oi da interface!'}).hover();await alice.locator('.message').filter({hasText:'Oi da interface!'}).getByTitle('Abrir tópico').click();await alice.getByLabel('Título do tópico',{exact:true}).fill('Nosso assunto');await alice.getByRole('button',{name:'Criar tópico',exact:true}).click();await alice.getByLabel('Responder no tópico',{exact:true}).fill('Resposta organizada em tópico');await alice.getByRole('button',{name:'Enviar resposta ao tópico'}).click();await alice.getByText('Resposta organizada em tópico',{exact:true}).waitFor();await alice.getByRole('button',{name:'Fechar',exact:true}).click();
 await alice.getByTitle('Buscar em todo o histórico').click();await alice.getByLabel('Texto da mensagem',{exact:true}).fill('Resposta organizada');await alice.getByRole('button',{name:'Buscar no histórico completo'}).click();await alice.locator('.search-result').filter({hasText:'Resposta organizada'}).waitFor();await alice.getByRole('button',{name:'Fechar',exact:true}).click();
 console.log('0.6: agendamentos');
 await alice.getByRole('button',{name:'Agendar',exact:true}).click();await alice.getByLabel('Mensagem agendada',{exact:true}).fill('Mensagem futura pela interface');const future=new Date(Date.now()+3600000);await alice.getByLabel('Data e hora local',{exact:true}).fill(new Date(future.getTime()-future.getTimezoneOffset()*60000).toISOString().slice(0,16));await alice.getByRole('button',{name:'Agendar mensagem',exact:true}).click();await alice.getByRole('button',{name:'Cancelar envio',exact:true}).click();await alice.getByText(/Cancelada/).waitFor();await alice.getByRole('button',{name:'Fechar',exact:true}).click();
 console.log('0.6: segurança e acessibilidade');
 await alice.getByRole('button',{name:'Configurações',exact:true}).click();await alice.getByRole('button',{name:'Segurança',exact:true}).click();await alice.getByLabel('Senha atual',{exact:true}).fill('Browser-test-password-123');await alice.getByRole('button',{name:'Gerar novos códigos de recuperação'}).click();await alice.locator('.recovery-sheet code').first().waitFor();assert.equal(await alice.locator('.recovery-sheet code').count(),8);await alice.getByRole('button',{name:'Já guardei os códigos'}).click();await alice.getByRole('button',{name:'Acessibilidade',exact:true}).click();await alice.getByLabel('Contraste reforçado',{exact:true}).check();await alice.getByLabel('Reduzir movimentos e animações',{exact:true}).check();await alice.getByRole('button',{name:'Salvar acessibilidade'}).click();await alice.waitForFunction(()=>document.documentElement.dataset.contrast==='true'&&document.documentElement.dataset.reduceMotion==='true');await alice.getByRole('button',{name:'Fechar',exact:true}).click();
 await alice.getByRole('button',{name:'Missões semanais',exact:true}).click();await alice.getByRole('heading',{name:'Missões da semana'}).waitFor();
 console.log('0.6: convite e perfil da comunidade');
 await alice.getByTitle('Criar ou entrar em comunidade',{exact:true}).click();await alice.getByLabel('Nome da comunidade',{exact:true}).fill('Comunidade seis');await alice.getByRole('button',{name:'Criar comunidade',exact:true}).click();await alice.getByRole('button',{name:'Convidar amigos',exact:true}).click();const link=await alice.getByRole('dialog').locator('code').innerText();await alice.getByRole('button',{name:'Fechar',exact:true}).click();await bob.goto(link);await bob.getByRole('button',{name:'Aceitar convite',exact:true}).click();await bob.getByRole('button',{name:'Perfil nesta comunidade',exact:true}).click();await bob.getByLabel('Apelido na comunidade',{exact:true}).fill('Lua azul');await bob.getByLabel('Bio na comunidade',{exact:true}).fill('Bio da turma');await bob.getByRole('button',{name:'Salvar perfil da comunidade'}).click();await bob.getByText('Perfil da comunidade salvo.',{exact:true}).waitFor();await bob.getByRole('button',{name:'Fechar',exact:true}).click();await bob.locator('.channel').filter({hasText:'geral'}).click();await bob.getByRole('textbox',{name:'Mensagem',exact:true}).fill('Meu apelido só aqui');await bob.getByRole('button',{name:'Enviar mensagem',exact:true}).click();await alice.locator('.channel').filter({hasText:'geral'}).click();await alice.locator('.message').filter({hasText:'Meu apelido só aqui'}).getByRole('button',{name:'Lua azul',exact:true}).waitFor();await alice.screenshot({path:'docs/screenshots/everyday-desktop.png',fullPage:true});await alice.setViewportSize({width:390,height:844});assert.equal(await alice.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await alice.screenshot({path:'docs/screenshots/everyday-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('Everyday browser PASS: áudio com reprodução, tópicos, busca, agendamento, recuperação, acessibilidade, convite e perfil local.');
}finally{if(browser)await browser.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}await rm(temp,{recursive:true,force:true});}

