import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const temp=await mkdtemp(path.join(tmpdir(),'nexo-touch-')),origin='http://localhost:3104';const server=spawn(process.execPath,['--import','tsx','apps/api/src/index.ts'],{cwd:process.cwd(),env:{...process.env,PORT:'3104',HOST:'127.0.0.1',APP_ORIGIN:origin,DATA_DIR:temp,DATABASE_URL:'',NODE_ENV:'development'},stdio:'pipe',windowsHide:true});let output='',browser;server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
try{
 for(let i=0;i<120;i++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(server.exitCode!==null)throw Error(output);await new Promise(r=>setTimeout(r,500));}
 browser=await chromium.launch({headless:true,channel:'msedge'});const a=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),b=await browser.newContext();a.setDefaultTimeout(15000);const page=await a.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));async function req(ctx,p,method='GET',data){const r=await ctx.request.fetch(origin+'/api'+p,{method,data,headers:{Origin:origin}});assert.ok(r.ok(),await r.text());return r.json();}
 await req(a,'/auth/register','POST',{username:'alice',password:'Browser-password-123'});await req(b,'/auth/register','POST',{username:'bobby',password:'Browser-password-123'});const am=(await req(a,'/state')).me;await req(a,'/friends','POST',{username:'bobby'});await req(b,'/friends/'+am.id+'/accept','POST');const room=await req(a,'/rooms','POST',{kind:'dm',name:'Teste mobile',users:['bobby']});await req(a,'/rooms/'+room.id+'/messages','POST',{body:'Segure esta mensagem'});await req(b,'/rooms/'+room.id+'/messages','POST',{body:'Mensagem do amigo'});
 await page.goto(origin);await page.getByTitle('Abrir menu').click();await page.locator('.conversation').click();await page.getByText('Segure esta mensagem',{exact:true}).waitFor();assert.equal(await page.locator('.message-tools').first().isVisible(),false);
 const cdp=await a.newCDPSession(page);const touch=(type,x,y)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'||type==='touchCancel'?[]:[{x,y}]});const hold=async locator=>{await locator.scrollIntoViewIfNeeded();const box=await locator.boundingBox();await touch('touchStart',box.x+box.width/2,box.y+box.height/2);await new Promise(r=>setTimeout(r,600));await touch('touchEnd');};
 await hold(page.getByText('Segure esta mensagem',{exact:true}));const sheet=page.getByRole('dialog',{name:'Opções da mensagem'});await sheet.waitFor();await sheet.getByRole('button',{name:'Favoritar',exact:true}).click();await sheet.waitFor({state:'detached'});assert.equal((await req(a,'/favorites')).length,1);
 await hold(page.getByText('Segure esta mensagem',{exact:true}));await sheet.getByRole('button',{name:'Responder',exact:true}).click();await page.locator('.replying').waitFor();await page.getByTitle('Cancelar resposta').click();
 await hold(page.getByText('Segure esta mensagem',{exact:true}));await sheet.getByRole('button',{name:'Editar',exact:true}).click();await page.getByRole('dialog',{name:'Editar mensagem'}).locator('textarea[name=body]').fill('Mensagem editada pelo menu');await page.getByRole('button',{name:'Salvar',exact:false}).click();await page.getByText('Mensagem editada pelo menu',{exact:true}).waitFor();
 await hold(page.getByText('Mensagem do amigo',{exact:true}));assert.equal(await sheet.getByRole('button',{name:'Editar',exact:true}).count(),0);await mkdir('docs/screenshots',{recursive:true});await page.screenshot({path:'docs/screenshots/mobile-message-menu.png'});await page.getByRole('button',{name:'Fechar opções'}).click();
 const box=await page.getByText('Mensagem do amigo',{exact:true}).boundingBox();await touch('touchStart',box.x+20,box.y+10);await touch('touchMove',box.x+20,box.y-35);await new Promise(r=>setTimeout(r,600));await touch('touchEnd');assert.equal(await sheet.count(),0);
 // Opening starts near the left edge, closing works inside the navigation.
 await touch('touchStart',18,170);await touch('touchMove',65,171);await touch('touchMove',145,172);await touch('touchEnd');await page.locator('.workspace.nav-open').waitFor();await touch('touchStart',240,350);await touch('touchMove',190,351);await touch('touchMove',110,351);await touch('touchEnd');await page.locator('.workspace.nav-open').waitFor({state:'detached'});
 await page.locator('.mobile-message-more').first().click();await sheet.waitFor();await page.keyboard.press('Escape');await sheet.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'docs/screenshots/mobile-chat-compact.png'});
 await page.setViewportSize({width:1440,height:960});await page.locator('.message').first().hover();assert.equal(await page.locator('.message-tools').first().isVisible(),true);assert.deepEqual(errors,[]);console.log('PASS: toque longo, favorito, responder, edição, menu acessível, cancelamento ao rolar, gestos de navegação e ações desktop preservadas.');
}finally{if(browser)await browser.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}await rm(temp,{recursive:true,force:true});}

