import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const temp=await mkdtemp(path.join(tmpdir(),'nexo-browser-'));
const origin='http://localhost:3101';
const server=spawn(process.execPath,['--import','tsx','apps/api/src/index.ts'],{cwd:process.cwd(),env:{...process.env,PORT:'3101',HOST:'127.0.0.1',APP_ORIGIN:origin,DATA_DIR:temp,DATABASE_URL:'',NODE_ENV:'development'},stdio:'pipe',windowsHide:true});
let output='';server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
let browser;
try{
 for(let attempt=0;attempt<120;attempt++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(server.exitCode!==null)throw new Error(output);await new Promise(r=>setTimeout(r,1000));}
 browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge',args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--autoplay-policy=no-user-gesture-required']});
 const a=await browser.newContext({viewport:{width:1440,height:960},permissions:['microphone','camera']});
 const b=await browser.newContext({viewport:{width:1440,height:960},permissions:['microphone','camera']});
 a.setDefaultTimeout(20000);b.setDefaultTimeout(20000);const errors=[];
 for(const ctx of [a,b])await ctx.addInitScript(()=>{window.__audioRequests=0;window.__captures=[];window.__noMic='';window.__cancelScreen=false;
const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
navigator.mediaDevices.getUserMedia=async c=>{if(c.audio){window.__audioRequests++;if(window.__noMic)throw new DOMException('Microfone simulado indisponível',window.__noMic);}const stream=await original(c);window.__captures.push(stream);return stream;};
navigator.mediaDevices.getDisplayMedia=async()=>{if(window.__cancelScreen)throw new DOMException('Cancelado','NotAllowedError');const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d');let frame=0;const paint=()=>{ctx.fillStyle=frame++%2?'#684ac4':'#76d9b1';ctx.fillRect(0,0,640,360);ctx.fillStyle='white';ctx.font='30px sans-serif';ctx.fillText('NexoChat • tela de teste '+frame,30,100);};paint();const timer=setInterval(paint,100);const stream=canvas.captureStream(10);window.__captures.push(stream);stream.getVideoTracks()[0].addEventListener('ended',()=>clearInterval(timer));return stream;};
window.__pcs=[];const Native=window.RTCPeerConnection;window.RTCPeerConnection=class extends Native{constructor(...args){super(...args);window.__pcs.push(this);}};});
 const alice=await a.newPage(),bob=await b.newPage();for(const p of [alice,bob])p.on('pageerror',e=>errors.push(e.message));
 for(const [p,name] of [[alice,'alice'],[bob,'bobby']]){
  await p.goto(origin);await p.getByRole('button',{name:'Criar minha conta'}).click();await p.getByLabel('Nome de usuário',{exact:true}).fill(name);await p.getByLabel('Senha',{exact:true}).fill('Browser-test-password-123');await p.getByRole('button',{name:'Criar conta',exact:true}).click();await p.getByRole('button',{name:'Adicionar amigo',exact:true}).waitFor();
 }
 await alice.getByRole('button',{name:'Adicionar amigo',exact:true}).click();await alice.getByRole('dialog').getByLabel('Nome de usuário',{exact:true}).fill('bobby');await alice.getByRole('button',{name:'Enviar solicitação'}).click();
 await bob.getByRole('button',{name:/Solicitações/}).click();await bob.getByRole('button',{name:'Aceitar',exact:true}).click();await bob.getByRole('button',{name:'Todos',exact:true}).click();
 await alice.getByRole('button',{name:'Mensagem para bobby',exact:true}).click();await alice.getByRole('textbox',{name:'Mensagem',exact:true}).fill('Oi da interface!');await alice.getByRole('button',{name:'Enviar mensagem',exact:true}).click();
 await bob.locator('.conversation').filter({hasText:'alice'}).click();await bob.getByText('Oi da interface!',{exact:true}).waitFor();await bob.getByRole('textbox',{name:'Mensagem',exact:true}).fill('Mensagem recebida em tempo real.');await bob.getByRole('button',{name:'Enviar mensagem',exact:true}).click();await alice.getByText('Mensagem recebida em tempo real.',{exact:true}).waitFor();
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z4Z8AAAAASUVORK5CYII=','base64');
 alice.on('response',r=>{if(r.status()>=400)console.log('HTTP failure',r.status(),r.url());});
 console.log('0.5: criando enquete');
 await alice.getByTitle('Criar enquete',{exact:true}).click();await alice.getByRole('dialog').getByLabel('Pergunta',{exact:true}).fill('Qual jogo hoje?');await alice.getByLabel('Opções (uma por linha, de 2 a 8)',{exact:true}).fill('Aventura\nCorrida');await alice.getByRole('button',{name:'Publicar enquete'}).click();
 console.log('0.5: votando');
 await alice.getByRole('dialog').waitFor({state:'detached'});
 const pollBob=bob.locator('.message').filter({hasText:'Qual jogo hoje?'});await pollBob.getByRole('button',{name:/Aventura/}).click();await pollBob.getByText('1 voto(s)',{exact:false}).waitFor();const pollAlice=alice.locator('.message').filter({hasText:'Qual jogo hoje?'});await pollAlice.getByTitle('Favoritar',{exact:true}).click();await pollAlice.getByTitle('Fixar',{exact:true}).click();await alice.locator('.pinned-panel summary').filter({hasText:'(1)'}).waitFor();await pollAlice.getByRole('button',{name:'Encerrar enquete'}).click();await pollBob.getByText('ENQUETE · ENCERRADA',{exact:true}).waitFor();
 console.log('0.5: favoritos');
 await alice.getByRole('button',{name:'Favoritos',exact:true}).click();await alice.getByRole('heading',{name:'Seus favoritos.'}).waitFor();await alice.getByText('Qual jogo hoje?',{exact:true}).waitFor();
 console.log('0.5: comunidade/evento');
 await alice.getByTitle('Criar ou entrar em comunidade',{exact:true}).click();await alice.getByLabel('Nome da comunidade',{exact:true}).fill('Turma dos testes');await alice.getByRole('button',{name:'Criar comunidade',exact:true}).click();await alice.getByRole('button',{name:'Painel da comunidade',exact:true}).click();await alice.getByText('Criar evento',{exact:true}).click();await alice.getByLabel('Título do evento',{exact:true}).fill('Noite de jogos');await alice.getByLabel('Descrição',{exact:true}).fill('Encontro da turma');const future=new Date(Date.now()+86400000);const localFuture=new Date(future.getTime()-future.getTimezoneOffset()*60000).toISOString().slice(0,16);await alice.getByLabel('Data e horário local',{exact:true}).fill(localFuture);await alice.getByRole('button',{name:'Publicar evento',exact:true}).click();await alice.getByRole('heading',{name:'Noite de jogos',exact:true}).waitFor();await alice.getByRole('button',{name:'Vou · 0',exact:true}).click();await alice.getByRole('button',{name:'Vou · 1',exact:true}).waitFor();await alice.screenshot({path:'docs/screenshots/events-desktop.png',fullPage:true});
 await alice.getByRole('button',{name:'Emojis e figurinhas',exact:true}).click();await alice.getByLabel('Nome do item',{exact:true}).fill('alegria');await alice.getByLabel('Imagem de até 2 MB',{exact:true}).setInputFiles({name:'emoji.png',mimeType:'image/png',buffer:png});await alice.getByRole('button',{name:'Adicionar à comunidade',exact:true}).click();await alice.getByText('Item adicionado!',{exact:true}).waitFor();await alice.getByRole('img',{name:'alegria',exact:true}).waitFor();
 await alice.getByLabel('Nome do item',{exact:true}).fill('gato');await alice.getByLabel('Tipo do item',{exact:true}).selectOption('sticker');await alice.getByRole('button',{name:'Adicionar à comunidade',exact:true}).click();await alice.getByRole('img',{name:'gato',exact:true}).waitFor();
 await alice.locator('.channel').filter({hasText:'geral'}).click();await alice.getByTitle('Emojis e figurinhas da comunidade',{exact:true}).click();await alice.getByRole('dialog').getByTitle('alegria',{exact:true}).click();await alice.getByRole('button',{name:'Enviar mensagem',exact:true}).click();await alice.locator('.inline-emoji').waitFor();await alice.getByTitle('Emojis e figurinhas da comunidade',{exact:true}).click();await alice.getByRole('dialog').getByTitle('gato',{exact:true}).click();await alice.locator('.message-sticker').waitFor();await alice.getByRole('button',{name:'Painel da comunidade',exact:true}).click();
 await alice.getByRole('button',{name:'Privacidade dos canais',exact:true}).click();await alice.locator('summary').filter({hasText:'geral'}).click();await alice.locator('details[open]').getByLabel('Canal privado',{exact:true}).check();await alice.locator('details[open]').getByLabel('Modo lento (segundos)',{exact:true}).fill('5');await alice.getByRole('button',{name:'Salvar canal geral',exact:true}).click();await alice.getByText('Permissões do canal atualizadas!',{exact:true}).waitFor();
 await alice.getByRole('button',{name:'Configurações',exact:true}).click();await alice.getByLabel('Tema do aplicativo',{exact:true}).selectOption('forest');await alice.getByLabel('Estilo do banner sem imagem',{exact:true}).selectOption('dots');await alice.getByRole('button',{name:'Salvar alterações',exact:true}).click();await alice.getByText('Perfil atualizado!',{exact:true}).waitFor();await alice.waitForFunction(()=>document.documentElement.dataset.theme==='forest');await alice.getByRole('button',{name:'Fechar',exact:true}).click();await alice.getByRole('button',{name:'Eventos',exact:true}).click();await alice.setViewportSize({width:390,height:844});assert.equal(await alice.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await alice.screenshot({path:'docs/screenshots/events-mobile.png',fullPage:true});
 console.log('PASS 0.5: enquetes, voto/encerramento, favoritos/fixados, eventos/presença, upload de emoji, canal privado, temas, pré-teste de microfone e destaque da tela.');
 await alice.setViewportSize({width:1440,height:960});await alice.getByTitle('Gerenciar comunidade',{exact:true}).click();await alice.getByRole('button',{name:'Excluir esta comunidade',exact:true}).click();assert.equal(await alice.getByRole('button',{name:'Excluir comunidade permanentemente'}).isDisabled(),true);await alice.getByLabel('Confirmar nome da comunidade').fill('Turma dos testes');await alice.getByRole('button',{name:'Excluir comunidade permanentemente'}).click();await alice.getByRole('dialog').waitFor({state:'detached'});await alice.getByTitle('Turma dos testes',{exact:true}).waitFor({state:'detached'});
 assert.deepEqual(errors,[]);console.log('Community browser PASS');
}finally{if(browser)await browser.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}await rm(temp,{recursive:true,force:true});}


