import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const temp=await mkdtemp(path.join(tmpdir(),'nexo-install-')),origin='http://localhost:3102';
const server=spawn(process.execPath,['--import','tsx','apps/api/src/index.ts'],{env:{...process.env,PORT:'3102',HOST:'127.0.0.1',APP_ORIGIN:origin,DATA_DIR:temp,DATABASE_URL:'',NODE_ENV:'development'},stdio:'pipe',windowsHide:true});let output='',browser;server.stderr.on('data',b=>output+=b);server.stdout.on('data',b=>output+=b);
try{
 for(let n=0;n<90;n++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}if(server.exitCode!==null)throw new Error(output);await new Promise(r=>setTimeout(r,1000));}
 browser=await chromium.launch({headless:true,channel:'msedge'});const ctx=await browser.newContext(),page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.getByRole('button',{name:'Instalar NexoChat',exact:true}).waitFor();
 const manifest=await (await fetch(origin+'/manifest.webmanifest')).json();assert.equal(manifest.display,'standalone');for(const icon of manifest.icons){const r=await fetch(origin+icon.src);assert.equal(r.status,200);const b=Buffer.from(await r.arrayBuffer());assert.equal(b.subarray(1,4).toString(),'PNG');assert.equal(b.readUInt32BE(16),Number(icon.sizes.split('x')[0]));}
 const cdp=await ctx.newCDPSession(page);const appManifest=await cdp.send('Page.getAppManifest');assert.equal(appManifest.errors.length,0);
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await page.evaluate(()=>{const event=new Event('beforeinstallprompt',{cancelable:true});window.__promptCalls=0;event.prompt=async()=>{window.__promptCalls++;};event.userChoice=Promise.resolve({outcome:'dismissed'});window.dispatchEvent(event);});await page.getByRole('button',{name:'Instalar NexoChat',exact:true}).click();await page.getByRole('button',{name:'Instalar neste aparelho'}).click();await page.getByText(/Instalação cancelada/).waitFor();assert.equal(await page.evaluate(()=>window.__promptCalls),1);await page.getByRole('button',{name:'Fechar instalação'}).click();
 await page.evaluate(()=>window.dispatchEvent(new Event('appinstalled')));assert.equal(await page.getByRole('button',{name:'Instalar NexoChat',exact:true}).count(),0);
 const cached=await page.evaluate(async()=>{const cache=await caches.open('nexochat-offline-v1');return (await cache.keys()).map(r=>new URL(r.url).pathname).sort();});assert.deepEqual(cached,['/offline.css','/offline.html']);await ctx.setOffline(true);await page.reload();await page.getByRole('heading',{name:'Você está sem conexão.'}).waitFor();assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(17, 21, 29)');assert.equal(await page.evaluate(async()=>{try{await fetch('/api/health');return true;}catch{return false;}}),false);
 const ios=await browser.newContext({viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});await ios.addInitScript(()=>window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();e.stopImmediatePropagation();},true));const phone=await ios.newPage();await phone.goto(origin);await phone.getByRole('button',{name:'Instalar NexoChat',exact:true}).click();await phone.getByText('Abra este site no Safari.',{exact:true}).waitFor();assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await phone.screenshot({path:'docs/screenshots/install-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: manifest, ícones PNG, diálogo, prompt único/cancelamento, instalado, instruções iPhone e modo offline sem cache privado. Instalação no sistema operacional não automatizada.');
}finally{if(browser)await browser.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}await rm(temp,{recursive:true,force:true});}

