import {useEffect,useState} from 'react';
import {Award,Check,Lock,Sparkles} from 'lucide-react';
import {api} from './api';
import {ProfileCard} from './ProfileSettings';
export default function Badges({me,reload}:{me:any,reload:()=>Promise<void>}){
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){setData(await api('/badges'));}useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function action(fn:()=>Promise<any>,message:string){setBusy(true);setError('');try{await fn();await load();await reload();setNotice(message);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const earned=data?.items.filter((b:any)=>b.earned_at).length||0;const ready=data?.items.filter((b:any)=>!b.earned_at&&b.progress>=b.target).length||0;
 function toggle(id:string){const next=data.displayed.includes(id)?data.displayed.filter((x:string)=>x!==id):[...data.displayed,id];if(next.length>3){setError('Escolha até três insígnias. Remova uma para trocar.');return;}void action(()=>api('/badges/display','POST',{ids:next}),'Vitrine do perfil atualizada!');}
 return <div className="shop-page badges-page"><header className="shop-hero"><div><span className="eyebrow"><Award size={15}/>CADA CONEXÃO CONTA UMA HISTÓRIA</span><h1>Pequenas conquistas.<br/>Grandes lembranças.</h1><p>Ganhe insígnias e Faíscas. Mostre no perfil o que combina com você.</p></div><div className="wallet"><Award/><strong>{earned}/{data?.items.length||8}</strong><span>Conquistas</span></div></header>
 <div className="badge-summary"><span><Sparkles size={18}/>{ready?ready+' recompensa(s) pronta(s) para resgatar':'Sua próxima conquista começa aqui.'}</span><span>Até 3 insígnias na vitrine · todas gratuitas</span></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="shop-notice" role="status"><Check size={16}/>{notice}</p>}
 <div className="shop-layout"><section><div className="tabs">{[['all','Todas'],['ready','Para resgatar'],['owned','Minhas insígnias']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</div>{!data?<p>Carregando conquistas…</p>:<div className="achievement-grid">{data.items.filter((b:any)=>tab==='all'||(tab==='owned'?b.earned_at:!b.earned_at&&b.progress>=b.target)).map((b:any)=><article key={b.id} className={'achievement '+(b.earned_at?'earned':'')}><div className="achievement-top"><span className="achievement-emblem" style={{color:b.color,borderColor:b.color}} aria-hidden="true">{b.icon}</span><small>{b.earned_at?'CONQUISTADA':b.progress>=b.target?'DISPONÍVEL':'EM PROGRESSO'}</small></div><h3>{b.name}</h3><p>{b.description}</p><label className="achievement-progress">{b.earned_at?'Concluída':b.progress+' / '+b.target}<progress aria-label={'Progresso '+b.name} value={b.earned_at?b.target:b.progress} max={b.target}/></label><footer><span>+{b.reward} ✦</span>{b.earned_at?<button disabled={busy} aria-pressed={data.displayed.includes(b.id)} onClick={()=>toggle(b.id)}>{data.displayed.includes(b.id)?'Ocultar do perfil':'Exibir no perfil'}</button>:<button className="primary" disabled={busy||b.progress<b.target} onClick={()=>void action(()=>api('/badges/claim','POST',{badge_id:b.id}),b.name+' conquistada! +'+b.reward+' Faíscas')}>{b.progress<b.target?<><Lock size={13}/>Bloqueada</>:'Resgatar conquista'}</button>}</footer>{b.earned_at&&<small>Desde {new Date(b.earned_at).toLocaleDateString('pt-BR')}</small>}</article>)}</div>}{data&&tab!=='all'&&!data.items.some((b:any)=>tab==='owned'?b.earned_at:!b.earned_at&&b.progress>=b.target)&&<div className="empty"><Award size={34}/><h3>{tab==='owned'?'Sua coleção está começando.':'Nenhum resgate pendente.'}</h3><p>Veja Todas para acompanhar suas conquistas.</p></div>}</section><aside className="shop-preview"><span className="eyebrow">SUA VITRINE · {data?.displayed.length||0}/3</span><ProfileCard user={{...me,displayed_badges:data?.displayed||[]}} preview/><p>Escolha as insígnias abaixo das conquistas. Elas aparecem na ordem em que você as adiciona.</p><button disabled={busy||!data?.displayed.length} onClick={()=>void action(()=>api('/badges/display','POST',{ids:[]}),'Vitrine limpa. Suas insígnias continuam na coleção.')}>Ocultar todas</button><p>As recompensas são únicas por conta. Insígnias são cosméticas: não concedem cargo ou poderes de moderação.</p></aside></div></div>;
}
