import {MicrophoneTest,SpeakingIndicator,SpeakerTest} from './CallExtras';
import {useEffect,useRef,useState} from 'react';
import {Mic,MicOff,Video,VideoOff,MonitorUp,PhoneOff,Headphones,Settings2,Maximize,Volume2,Smartphone,Monitor,Users,X} from 'lucide-react';
import AudioMeter from './AudioMeter';
import {api} from './api';
import type {Socket} from 'socket.io-client';
import {CallEngine,type JoinMode,type RemotePeer} from './call-engine';
function VideoTile({stream,name,screen=false,focused=false,onFocus}:{stream:MediaStream,name:string,screen?:boolean,focused?:boolean,onFocus?:()=>void}){
 const ref=useRef<HTMLVideoElement>(null);const [blocked,setBlocked]=useState(false);
 useEffect(()=>{const v=ref.current;if(v){v.srcObject=stream;void v.play().catch(()=>setBlocked(true));}},[stream]);
 return <div className={'video-tile '+(screen?'screen-tile':'')+(focused?' featured-video':'')}><video ref={ref} autoPlay playsInline muted/>{blocked&&<button className="resume-media" onClick={()=>void ref.current?.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true))}>Reproduzir vídeo</button>}<span>{screen?<Monitor size={13}/>:<Video size={13}/>} {name}</span><>{onFocus&&<button className="feature-video" title={focused?'Tirar destaque':'Destacar transmissão'} onClick={onFocus}>{focused?'Reduzir':'Destacar'}</button>}</><button title={'Expandir '+name} className="expand-video" onClick={()=>{void ref.current?.requestFullscreen?.().catch(()=>{});}}><Maximize size={16}/></button></div>;
}
function RemoteAudio({stream,deaf,suppressed,volume,sink}:{stream:MediaStream,deaf:boolean,suppressed:boolean,volume:number,sink:string}){
 const ref=useRef<HTMLAudioElement>(null),suppressedRef=useRef(suppressed);suppressedRef.current=suppressed;
 const [blocked,setBlocked]=useState(false),[outputError,setOutputError]=useState(false);const muted=deaf||suppressed;
 useEffect(()=>{const a=ref.current;if(!a)return;let disposed=false;const tracks=new Set<MediaStreamTrack>();a.setAttribute('playsinline','');a.srcObject=stream;
  const play=()=>{if(!stream.getAudioTracks().length||disposed)return;void a.play().then(()=>{if(!disposed)setBlocked(false);}).catch(()=>{if(!disposed&&!a.muted)setBlocked(true);});};
  const attach=()=>{for(const t of stream.getAudioTracks())if(!tracks.has(t)){tracks.add(t);t.addEventListener('unmute',play);}play();};
  // Run play synchronously inside the user's click, including when React has not
  // yet applied the updated deafen state. Never unlock one's own device implicitly.
  const resume=()=>{if(!suppressedRef.current){a.muted=false;play();}};attach();stream.addEventListener('addtrack',attach);window.addEventListener('nexo-play-audio',resume);
  return()=>{disposed=true;stream.removeEventListener('addtrack',attach);window.removeEventListener('nexo-play-audio',resume);for(const t of tracks)t.removeEventListener('unmute',play);a.pause();a.srcObject=null;};
 },[stream]);
 useEffect(()=>{const a=ref.current;if(!a)return;a.muted=muted;if(!muted&&stream.getAudioTracks().length)void a.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true));},[muted,stream]);
 useEffect(()=>{if(ref.current)ref.current.volume=volume/100;},[volume]);
 useEffect(()=>{const a=ref.current as HTMLAudioElement&{setSinkId?:(s:string)=>Promise<void>};if(a?.setSinkId)void a.setSinkId(sink).then(()=>setOutputError(false)).catch(()=>setOutputError(true));},[sink]);
 return <><audio ref={ref} autoPlay muted={muted} data-call-audio="true"/>{blocked&&!muted&&<button className="resume-media" onClick={()=>{const a=ref.current;if(a){a.muted=false;void a.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true));}}}>Ativar áudio</button>}{blocked&&!muted&&<small>O navegador bloqueou o som. Toque em Ativar áudio.</small>}{outputError&&<small>Saída indisponível; selecione Padrão.</small>}</>;
}
function Participant({p,deaf,me,sink,monitorOwn,volume,onVolume}:{p:RemotePeer,deaf:boolean,me:string,sink:string,monitorOwn:boolean,volume:number,onVolume:(peer:string,v:number)=>void}){
 const same=p.user_id===me;
 return <div className={'call-person '+(same?'same-account':'')}><span className="call-person-avatar">{same?<Smartphone size={24}/>:p.name.slice(0,2).toUpperCase()}</span><div><strong>{p.name}{same?' · seu outro dispositivo':''}</strong><SpeakingIndicator stream={p.audio} enabled={p.media.mic}/><small>{p.connection==='connected'?(p.media.mic?'Microfone ligado':'Só ouvindo / microfone mudo'):p.connection==='failed'?'Falha de conexão':'Conectando mídia…'}</small><small className={'quality-chip '+(p.lossPercent!=null&&p.lossPercent>5||p.rttMs!=null&&p.rttMs>300?'poor':p.rttMs!=null&&p.rttMs>150?'fair':'good')}>{p.connection!=='connected'?'Qualidade: aguardando conexão':p.rttMs==null?'Qualidade: medindo…':(p.lossPercent!=null&&p.lossPercent>5||p.rttMs>300?'Qualidade baixa':p.rttMs>150?'Qualidade regular':'Qualidade boa')+' · '+Math.round(p.rttMs)+' ms'}{p.lossPercent!=null?' · perda '+p.lossPercent.toFixed(1)+'%':''}</small></div><span title={p.media.mic?'Microfone ligado':'Microfone desligado'}>{p.media.mic?<Mic size={16}/>:<MicOff size={16}/>}</span>{p.media.deaf&&<Headphones size={16}/>}<label className="peer-volume" title="Volume individual"><Volume2 size={14}/><input aria-label={'Volume de '+p.name} type="range" min="0" max="100" value={volume} onChange={e=>onVolume(p.user_id,Number(e.target.value))}/></label><RemoteAudio stream={p.audio} deaf={deaf} suppressed={same&&!monitorOwn} volume={volume} sink={sink}/><RemoteAudio stream={p.screenAudio} deaf={deaf} suppressed={same} volume={volume} sink={sink}/></div>;
}
export default function Call({socket,room,me,onEnd,onError}:{socket:Socket,room:any,me:string,onEnd:()=>void,onError:(s:string)=>void}){
 const [mode,setMode]=useState<JoinMode|null>(room.joinMode||null);
 if(!mode)return <section className="call call-lobby"><div className="call-lobby-heading"><span className="call-lobby-icon"><Headphones size={27}/></span><div><span className="eyebrow">ENCONTRE SUA TURMA</span><h2>Como você quer entrar?</h2><p>{room.name} · Você pode mudar os controles durante a chamada.</p></div><button title="Cancelar chamada" onClick={onEnd}><X/></button></div><div className="join-options"><button onClick={()=>setMode('voice')}><Mic/><strong>Conversar</strong><span>Entrar com seu microfone.<br/>Se não houver um, você entra ouvindo.</span></button><button onClick={()=>setMode('listen')}><Headphones/><strong>Só ouvir</strong><span>Sem pedir acesso ao microfone.<br/>Você também pode compartilhar a tela.</span></button><button onClick={()=>setMode('companion')}><Monitor/><strong>Usar PC com celular</strong><span>Áudio e microfone desligados no PC.<br/>Use o celular para falar e ouvir.</span><b>IDEAL PARA O SEU CASO</b></button></div><MicrophoneTest/><SpeakerTest/><p className="call-help">Entre na mesma conta e conversa pelo celular. No PC, clique em Compartilhar tela depois de entrar.</p></section>;
 return <ActiveCall socket={socket} room={room} me={me} mode={mode} onEnd={onEnd} onError={onError}/>;
}
function ActiveCall({socket,room,me,mode,onEnd,onError}:{socket:Socket,room:any,me:string,mode:JoinMode,onEnd:()=>void,onError:(s:string)=>void}){
 const engineRef=useRef<CallEngine|null>(null);const [,render]=useState(0);const callbacks=useRef({onEnd,onError});callbacks.current={onEnd,onError};
 const [volumes,setVolumes]=useState<Record<string,number>>({});const saveTimers=useRef<Record<string,ReturnType<typeof setTimeout>>>({});const changedVolumes=useRef(new Set<string>());useEffect(()=>{let live=true;void api('/call-preferences').then(rows=>{if(live)setVolumes(old=>({...Object.fromEntries(rows.filter((r:any)=>!changedVolumes.current.has(r.peer_id)).map((r:any)=>[r.peer_id,r.volume])),...old}));}).catch(e=>callbacks.current.onError(e.message));return()=>{live=false;for(const timer of Object.values(saveTimers.current))clearTimeout(timer);};},[me]);
 const saveVolume=(peer:string,volume:number)=>{changedVolumes.current.add(peer);setVolumes(old=>({...old,[peer]:volume}));clearTimeout(saveTimers.current[peer]);saveTimers.current[peer]=setTimeout(()=>{void api('/call-preferences/'+peer,'PUT',{volume}).catch(e=>callbacks.current.onError('Não foi possível salvar o volume: '+e.message));delete saveTimers.current[peer];},300);};
 const [focusKey,setFocusKey]=useState<string|null>(null);
 const [monitorOwn,setMonitorOwn]=useState(false),[ringNote,setRingNote]=useState(''),[outgoing,setOutgoing]=useState<any[]>([]);
 const [settings,setSettings]=useState(false),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[mic,setMic]=useState(''),[cam,setCam]=useState(''),[sink,setSink]=useState(''),[quality,setQuality]=useState<'720'|'1080'>('1080'),[screenAudio,setScreenAudio]=useState(true),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState(false);
 const refreshDevices=async()=>{if(navigator.mediaDevices?.enumerateDevices)try{setDevices(await navigator.mediaDevices.enumerateDevices());}catch{}};
 useEffect(()=>{const engine=new CallEngine(socket,room.id,mode,()=>render(n=>n+1),s=>callbacks.current.onError(s),()=>callbacks.current.onEnd());engineRef.current=engine;void engine.start().then(async()=>{await refreshDevices();if(engine.ready&&!engine.disposed&&!room.acceptedCall&&!room.server_id&&engine.peers.size===0){try{const r=await api('/rooms/'+room.id+'/ring','POST',{socket_id:socket.id});if(!engine.disposed){setOutgoing(r.rings);setRingNote(r.message);}}catch(e:any){if(!engine.disposed)setRingNote(e.message);}}});navigator.mediaDevices?.addEventListener('devicechange',refreshDevices);return()=>{engine.dispose();navigator.mediaDevices?.removeEventListener('devicechange',refreshDevices);};},[room.id,socket,mode]);
 useEffect(()=>{const result=(r:any)=>{if(r.room!==room.id)return;setOutgoing(old=>old.filter(x=>x.id!==r.id));setRingNote(({accepted:'Chamada aceita',declined:'Chamada recusada',missed:'Chamada não atendida',busy:'Pessoa ocupada',cancelled:'Chamada cancelada'} as any)[r.status]||'');};socket.on('ring-result',result);const t=setInterval(()=>{void engineRef.current?.stats();},3000);return()=>{socket.off('ring-result',result);clearInterval(t);};},[socket,room.id]);
 const engine=engineRef.current;
 const act=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);try{await fn();await refreshDevices();}catch(e:any){if(e.name!=='NotAllowedError')onError(e.message);else onError('Permissão cancelada. Você continua na chamada; tente novamente quando quiser.');}finally{setBusy(false);}};
 const peers=[...(engine?.peers.values()||[])],media=engine?.media;
 const camera=engine?.tracks[1],screen=engine?.tracks[2];
 const cameraStream=useRef<{track:MediaStreamTrack|null,stream:MediaStream}>({track:null,stream:new MediaStream()}),screenStream=useRef<{track:MediaStreamTrack|null,stream:MediaStream}>({track:null,stream:new MediaStream()});
 if(camera!==cameraStream.current.track)cameraStream.current={track:camera||null,stream:new MediaStream(camera?[camera]:[])};
 if(screen!==screenStream.current.track)screenStream.current={track:screen||null,stream:new MediaStream(screen?[screen]:[])};
 return <section className={'call call-v2 '+(expanded?'call-expanded':'')}><div className="call-heading"><span className="live-dot"/><strong>{room.name}</strong><small>{engine?.ready?'Na sala · confira o áudio dos participantes':'Conectando…'}</small><span className="pill"><Users size={11}/>{peers.length+1}/6 dispositivos</span><button title={expanded?'Reduzir chamada':'Ampliar chamada'} onClick={()=>setExpanded(!expanded)}><Maximize size={16}/></button></div>
 {mode==='companion'&&<div className="companion-hint"><Smartphone size={16}/><span>PC + celular: fale e ouça no celular. Neste PC, compartilhe a tela sem eco.</span></div>}{engine?.note&&<div className="call-note" role="status">{engine.note}</div>}
 {ringNote&&<div className="outgoing-call"><span>{ringNote}</span>{outgoing.length>0&&<button onClick={()=>void act(async()=>{await Promise.all(outgoing.map(r=>api('/rings/'+r.id,'DELETE')));setOutgoing([]);setRingNote('Convite cancelado. Você continua na sala.');})}>Cancelar ligação</button>}</div>}
 <div className="audio-quick"><AudioMeter track={engine?.tracks[0]} enabled={!!media?.mic}/><button onClick={()=>{if(engine?.media.deaf)engine.toggleDeaf();window.dispatchEvent(new Event('nexo-play-audio'));}}>Ativar som</button></div>
 <div className="video-grid">{media?.screen&&<VideoTile stream={screenStream.current.stream} name="Sua tela" screen focused={focusKey==='self'} onFocus={()=>setFocusKey(k=>k==='self'?null:'self')}/>}{peers.filter(p=>p.media.screen).map(p=><VideoTile key={p.id+'screen'} stream={p.screen} name={'Tela de '+p.name} screen focused={focusKey===p.id} onFocus={()=>setFocusKey(k=>k===p.id?null:p.id)}/>)}{media?.camera&&<VideoTile stream={cameraStream.current.stream} name="Sua câmera"/>}{peers.filter(p=>p.media.camera).map(p=><VideoTile key={p.id+'camera'} stream={p.camera} name={'Câmera de '+p.name}/>)}</div>
 <div className="call-people"><div className="call-person self-person"><span className="call-person-avatar">{mode==='companion'?<Monitor size={23}/>:<Headphones size={23}/>}</span><div><strong>Você · este dispositivo</strong><small>{media?.mic?'Microfone ligado':media?.deaf?'Áudio desligado neste dispositivo':'Só ouvindo'}{media?.screen?' · transmitindo tela':''}</small></div>{media?.mic?<Mic size={16}/>:<MicOff size={16}/>}</div>{peers.map(p=><Participant key={p.id} p={p} deaf={!!media?.deaf} me={me} sink={sink} monitorOwn={monitorOwn} volume={volumes[p.user_id]??100} onVolume={saveVolume}/>)}</div>
 <div className="call-controls"><button title="Microfone" aria-pressed={!!media?.mic} disabled={busy||!engine?.ready} className={!media?.mic?'danger':''} onClick={()=>void act(()=>engine!.toggleMic())}>{media?.mic?<Mic/>:<MicOff/>}</button><button title="Câmera" aria-pressed={!!media?.camera} disabled={busy||!engine?.ready} onClick={()=>void act(()=>engine!.camera(cam))}>{media?.camera?<Video/>:<VideoOff/>}</button><button title="Compartilhar tela" aria-pressed={!!media?.screen} className={media?.screen?'active share-action':'share-action'} disabled={busy||!engine?.ready} onClick={()=>void act(()=>engine!.share(quality,screenAudio))}><MonitorUp/><span>{media?.screen?'Parar tela':'Compartilhar tela'}</span></button><button title="Ensurdecer" aria-pressed={!!media?.deaf} className={media?.deaf?'danger':''} disabled={!engine?.ready} onClick={()=>engine?.toggleDeaf()}><Headphones/></button><button title="Dispositivos" onClick={()=>setSettings(!settings)}><Settings2/></button><button className="danger-solid" title="Sair da chamada" onClick={onEnd}><PhoneOff/></button></div>
 {settings&&<div className="device-settings"><div className="audio-diagnostics"><strong>Diagnóstico de áudio</strong><SpeakerTest sink={sink}/><small>A qualidade estima atraso e perda recente de pacotes. Não confirma que o alto-falante está reproduzindo som.</small><p>{engine?.turnConfigured?'TURN configurado. Isso não confirma que as credenciais ou o servidor estão funcionando.':'Conexão direta. Redes restritivas podem precisar de um servidor TURN.'}</p>{peers.map(p=><small key={p.id}>{p.name}: {p.route} · {p.pc.iceConnectionState} · enviado {Math.round(p.audioSent/1024)} KB · recebido {Math.round(p.audioReceived/1024)} KB · {p.audioReceiving?'Áudio chegando agora':p.connection==='connected'?'Sem novos pacotes de áudio':'Aguardando conexão'} · {p.audioSending?'Enviando áudio':'Sem novos pacotes enviados'}{p.user_id===me?' · mesma conta (silenciada por padrão)':''}</small>)}<p>Se a tela aparece e o áudio chega, toque em Ativar som, confira o volume do aparelho e a saída de áudio. O modo PC + celular desliga o som do PC. A mesma conta em dois dispositivos fica silenciada entre eles para evitar eco.</p><button onClick={()=>void act(()=>engine!.reconnect())}>Reconectar mídia</button></div><label className="check"><input type="checkbox" checked={monitorOwn} onChange={e=>{setMonitorOwn(e.target.checked);if(e.target.checked&&engine?.media.deaf)engine.toggleDeaf();}}/>Ouvir meu outro dispositivo (teste com fones)</label><label>Microfone<select value={mic} disabled={busy} onChange={e=>{const v=e.target.value;void act(async()=>{await engine!.microphone(v);setMic(v);});}}><option value="">Padrão do sistema</option>{devices.filter(d=>d.kind==='audioinput').map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||'Microfone'}</option>)}</select></label><label>Câmera (próxima ativação)<select value={cam} onChange={e=>setCam(e.target.value)}><option value="">Padrão do sistema</option>{devices.filter(d=>d.kind==='videoinput').map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||'Câmera'}</option>)}</select></label>{'setSinkId' in HTMLMediaElement.prototype&&<label>Saída de áudio<select value={sink} onChange={e=>setSink(e.target.value)}><option value="">Padrão do sistema</option>{devices.filter(d=>d.kind==='audiooutput').map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||'Saída de áudio'}</option>)}</select></label>}<label>Qualidade da próxima transmissão<select value={quality} onChange={e=>setQuality(e.target.value as '720'|'1080')}><option value="720">720p · menos banda</option><option value="1080">1080p · mais detalhes</option></select></label><label className="check"><input type="checkbox" checked={screenAudio} onChange={e=>setScreenAudio(e.target.checked)}/>Incluir áudio da tela quando o navegador permitir</label><small>Marque também “Compartilhar áudio” no seletor do navegador. Câmera e tela podem funcionar juntas. A qualidade final depende da rede e da tela capturada.</small></div>}
 </section>;
}
