import {useEffect,useRef,useState} from 'react';
import {Mic,MicOff,Video,VideoOff,MonitorUp,PhoneOff,Headphones,Settings2} from 'lucide-react';
import type {Socket} from 'socket.io-client';
import {api} from './api';
type Peer={pc:RTCPeerConnection;name:string;stream:MediaStream;makingOffer:boolean;ignoreOffer:boolean;pending:RTCIceCandidateInit[]};
function Media({stream,muted,name}:{stream:MediaStream,muted:boolean,name:string}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current){ref.current.srcObject=stream;void ref.current.play().catch(()=>{});}},[stream]);return <div className="video-tile"><video ref={ref} autoPlay playsInline muted={muted}/><span>{name}</span></div>;}
export default function Call({socket,room,onEnd,onError}:{socket:Socket,room:any,onEnd:()=>void,onError:(s:string)=>void}){
 const local=useRef<MediaStream|null>(null),peers=useRef(new Map<string,Peer>()),config=useRef<RTCConfiguration>({});
 const [self,setSelf]=useState<MediaStream|null>(null),[remote,setRemote]=useState<{id:string,name:string,stream:MediaStream}[]>([]),[muted,setMuted]=useState(false),[deaf,setDeaf]=useState(false),[camera,setCamera]=useState(false),[sharing,setSharing]=useState(false),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[settings,setSettings]=useState(false),[mic,setMic]=useState(''),[cam,setCam]=useState(''),[status,setStatus]=useState('Conectando…');
 const screen=useRef<MediaStream|null>(null);const alive=useRef(true);const muteRef=useRef(false);const shareRef=useRef(false);
 const sync=()=>setRemote([...peers.current].map(([id,p])=>({id,name:p.name,stream:p.stream})));
 function signal(to:string,p:any){socket.emit('signal',{to,...p},(r:any)=>{if(!r.ok)onError(r.error);});}
 function peer(id:string,name:string){let p=peers.current.get(id);if(p)return p;const pc=new RTCPeerConnection(config.current);p={pc,name,stream:new MediaStream(),makingOffer:false,ignoreOffer:false,pending:[]};peers.current.set(id,p);const item=p;
   for(const track of local.current?.getTracks()||[])pc.addTrack(track,local.current!);
   pc.ontrack=e=>{for(const t of e.streams[0]?.getTracks()||[e.track])if(!item.stream.getTrackById(t.id))item.stream.addTrack(t);sync();};
   pc.onicecandidate=e=>{if(e.candidate)signal(id,{candidate:e.candidate.toJSON()});};
   pc.onnegotiationneeded=async()=>{try{item.makingOffer=true;await pc.setLocalDescription();signal(id,{description:pc.localDescription});}catch(e:any){onError(e.message);}finally{item.makingOffer=false;}};
   pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed')onError('A conexão de mídia falhou. Configure TURN para redes restritivas e entre novamente.');};return item;
 }
 useEffect(()=>{alive.current=true;let cancelled=false;
   const receive=async(data:any)=>{try{const p=peer(data.from,data.name),pc=p.pc;if(data.description){const collision=data.description.type==='offer'&&(p.makingOffer||pc.signalingState!=='stable');const polite=socket.id!>data.from;p.ignoreOffer=!polite&&collision;if(p.ignoreOffer)return;await pc.setRemoteDescription(data.description);for(const c of p.pending)await pc.addIceCandidate(c);p.pending=[];if(data.description.type==='offer'){await pc.setLocalDescription();signal(data.from,{description:pc.localDescription});}}else if(data.candidate){if(p.ignoreOffer)return;if(pc.remoteDescription)await pc.addIceCandidate(data.candidate);else p.pending.push(data.candidate);}}catch(e:any){onError(e.message);}};
   const left=({peer:id}:{peer:string})=>{peers.current.get(id)?.pc.close();peers.current.delete(id);sync();};
   const lost=()=>{onError('Chamada encerrada: conexão ou acesso alterado.');onEnd();};
   void(async()=>{try{config.current=await api('/rtc-config');const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});if(cancelled){stream.getTracks().forEach(t=>t.stop());return;}local.current=stream;setSelf(new MediaStream(stream.getTracks()));setDevices(await navigator.mediaDevices.enumerateDevices());socket.on('signal',receive);socket.on('call-left',left);socket.on('disconnect',lost);socket.on('call-ended',lost);socket.emit('call-join',{room:room.id},(r:any)=>{if(cancelled)return;if(!r.ok){onError(r.error);onEnd();return;}setStatus('Conectado · áudio em tempo real');for(const p of r.peers)peer(p.id,p.name);});}catch(e:any){onError('Não foi possível abrir o microfone: '+e.message);onEnd();}})();
   return()=>{cancelled=true;alive.current=false;socket.off('signal',receive);socket.off('call-left',left);socket.off('disconnect',lost);socket.off('call-ended',lost);socket.emit('call-leave',{});local.current?.getTracks().forEach(t=>t.stop());screen.current?.getTracks().forEach(t=>t.stop());for(const p of peers.current.values())p.pc.close();peers.current.clear();};
 },[room.id,socket]);
 async function replaceVideo(track:MediaStreamTrack|null){for(const [pid,p] of peers.current){const sender=p.pc.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(track);else if(track)p.pc.addTrack(track,local.current!);}
   const old=local.current?.getVideoTracks()||[];for(const t of old){local.current?.removeTrack(t);if(t!==track)t.stop();}if(track)local.current?.addTrack(track);setSelf(new MediaStream(local.current?.getTracks()||[]));}
 async function toggleCamera(){try{if(shareRef.current){onError('Pare o compartilhamento antes de ligar a câmera.');return;}if(camera){await replaceVideo(null);setCamera(false);}else{const s=await navigator.mediaDevices.getUserMedia({video:cam?{deviceId:{exact:cam}}:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}await replaceVideo(s.getVideoTracks()[0]);setCamera(true);setDevices(await navigator.mediaDevices.enumerateDevices());}}catch(e:any){onError(e.message);}}
 async function stopShare(){screen.current?.getTracks().forEach(t=>t.stop());screen.current=null;await replaceVideo(null);shareRef.current=false;setSharing(false);setCamera(false);}
 async function share(){try{if(sharing){await stopShare();return;}const s=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}screen.current=s;await replaceVideo(s.getVideoTracks()[0]);shareRef.current=true;setSharing(true);setCamera(false);s.getVideoTracks()[0].onended=()=>void stopShare();}catch(e:any){if(e.name!=='NotAllowedError')onError(e.message);}}
 async function selectMic(value:string){try{const s=await navigator.mediaDevices.getUserMedia({audio:value?{deviceId:{exact:value}}:true});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}const t=s.getAudioTracks()[0];t.enabled=!muteRef.current;for(const p of peers.current.values()){const sender=p.pc.getSenders().find(s=>s.track?.kind==='audio');if(sender)await sender.replaceTrack(t);}local.current?.getAudioTracks().forEach(old=>{old.stop();local.current?.removeTrack(old);});local.current?.addTrack(t);setMic(value);}catch(e:any){onError(e.message);}}
 return <section className="call"><div className="call-heading"><span className="live-dot"/><strong>{room.name}</strong><small>{status}</small><span className="pill">{remote.length+1}/6 pessoas</span></div><div className="video-grid">{self&&<Media stream={self} muted name="Você"/>}{remote.map(p=><Media key={p.id} stream={p.stream} muted={deaf} name={p.name}/>)}</div><div className="call-controls"><button title="Microfone" className={muted?'danger':''} onClick={()=>{muteRef.current=!muted;local.current?.getAudioTracks().forEach(t=>t.enabled=muted);setMuted(!muted);}}>{muted?<MicOff/>:<Mic/>}</button><button title="Câmera" onClick={()=>void toggleCamera()}>{camera?<Video/>:<VideoOff/>}</button><button title="Compartilhar tela" className={sharing?'active':''} onClick={()=>void share()}><MonitorUp/></button><button title="Ensurdecer" className={deaf?'danger':''} onClick={()=>{setDeaf(!deaf);if(!deaf){muteRef.current=true;setMuted(true);local.current?.getAudioTracks().forEach(t=>t.enabled=false);}}}><Headphones/></button><button title="Dispositivos" onClick={()=>setSettings(!settings)}><Settings2/></button><button className="danger-solid" title="Sair da chamada" onClick={onEnd}><PhoneOff/></button></div>{settings&&<div className="device-settings"><label>Microfone<select value={mic} onChange={e=>void selectMic(e.target.value)}><option value="">Padrão do sistema</option>{devices.filter(d=>d.kind==='audioinput').map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||'Microfone'}</option>)}</select></label><label>Câmera (próxima ativação)<select value={cam} onChange={e=>setCam(e.target.value)}><option value="">Padrão do sistema</option>{devices.filter(d=>d.kind==='videoinput').map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||'Câmera'}</option>)}</select></label><small>Saída de áudio: use as configurações do sistema. Compartilhamento de tela sem áudio.</small></div>}</section>;
}
