import {useEffect,useState,type ReactNode} from 'react';
import {api} from './api';
export function FeatureForm({children,onSubmit,label='Salvar'}:{children:ReactNode,onSubmit:(d:FormData)=>Promise<any>,label?:string}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="form feature-form" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await onSubmit(d);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{children}{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Salvando…':label}</button></form>;}
const localDate=(iso:string)=>{const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function CommunityHub({server,me,reload,revision}:{server:any,me:any,reload:()=>Promise<void>,revision:any}){
 const [creating,setCreating]=useState(false);
 const [data,setData]=useState<any>(null),[tab,setTab]=useState('events'),[reports,setReports]=useState<any[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const d=await api('/servers/'+server.id+'/hub');setData(d);if(d.canModerate)setReports(await api('/servers/'+server.id+'/reports'));else setReports([]);}
 useEffect(()=>{let live=true;void api('/servers/'+server.id+'/hub').then(async d=>{if(!live)return;setData(d);if(d.canModerate){const rs=await api('/servers/'+server.id+'/reports');if(live)setReports(rs);}else setReports([]);}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[server.id,revision]);
 async function action(fn:()=>Promise<any>,message='Atualizado!'){if(busy)return;setBusy(true);setError('');try{await fn();await load();await reload();setNotice(message);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const saveEvent=(e:any,d:FormData)=>api(e?'/events/'+e.id:'/servers/'+server.id+'/events',e?'PATCH':'POST',{title:d.get('title'),description:d.get('description'),starts_at:new Date(String(d.get('starts_at'))).toISOString(),...(e?{cancelled:false}:{})});
 const eventFields=(e?:any)=><><label>Título do evento<input name="title" required maxLength={80} defaultValue={e?.title}/></label><label>Descrição<textarea name="description" maxLength={1000} defaultValue={e?.description||''}/></label><label>Data e horário local<input type="datetime-local" name="starts_at" required defaultValue={e?localDate(e.starts_at):''}/></label></>;
 return <div className="page-content community-hub"><header className="feature-hero"><span className="eyebrow">O PONTO DE ENCONTRO DA TURMA</span><h1>{server.name}</h1><p>Combine o próximo rolê. Dê uma cara à comunidade.</p></header><div className="tabs"><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}>Eventos</button><button className={tab==='assets'?'active':''} onClick={()=>setTab('assets')}>Emojis e figurinhas</button>{data?.canManage&&<button className={tab==='channels'?'active':''} onClick={()=>setTab('channels')}>Privacidade dos canais</button>}{data?.canModerate&&<button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}>Denúncias</button>}</div>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="shop-notice">{notice}</p>}{!data?<p>Carregando comunidade…</p>:<>
 {tab==='events'&&<><div className="feature-info">Os horários aparecem no seu fuso. Confirme presença para a turma saber quem vai. Sem notificações push nesta versão.</div>{data.canCreate&&<details className="feature-card" open={creating} onToggle={e=>setCreating(e.currentTarget.open)}><summary>Criar evento</summary><FeatureForm label="Publicar evento" onSubmit={async d=>{await saveEvent(null,d);await load();await reload();setNotice('Evento publicado!');setCreating(false);}}>{eventFields()}</FeatureForm></details>}<div className="event-grid">{data.events.map((e:any)=>{const ended=e.cancelled||new Date(e.starts_at).getTime()<Date.now(),mine=e.attendees.find((a:any)=>a.user_id===me.id)?.response;return <article className="feature-card event-card" key={e.id}><small>{e.cancelled?'CANCELADO':ended?'JÁ ACONTECEU':new Date(e.starts_at).toLocaleString('pt-BR')}</small><h2>{e.title}</h2><p>{e.description}</p><small>Por {e.display_name}</small><div className="rsvp">{[['going','Vou'],['maybe','Talvez'],['declined','Não vou']].map(([k,n])=><button key={k} aria-pressed={mine===k} disabled={busy||ended} onClick={()=>void action(()=>api('/events/'+e.id+'/rsvp','POST',{response:k}),'Presença atualizada!')}>{n} · {e.attendees.filter((a:any)=>a.response===k).length}</button>)}</div><details><summary>Quem confirmou</summary>{e.attendees.filter((a:any)=>a.response==='going').map((a:any)=><p key={a.user_id}>{a.display_name}</p>)}{!e.attendees.some((a:any)=>a.response==='going')&&<p>Ninguém confirmou ainda.</p>}</details>{(e.creator_id===me.id||data.canManage)&&!e.cancelled&&<details><summary>Editar ou cancelar</summary><FeatureForm onSubmit={async d=>{await saveEvent(e,d);await load();await reload();}}>{eventFields(e)}</FeatureForm><button disabled={busy} className="danger" onClick={()=>void action(()=>api('/events/'+e.id,'PATCH',{title:e.title,description:e.description,starts_at:new Date(e.starts_at).toISOString(),cancelled:true}),'Evento cancelado.')}>Cancelar evento</button></details>}</article>;})}</div>{!data.events.length&&<p className="empty">Nenhum evento ainda. Que tal marcar uma partida?</p>}</>}
 {tab==='assets'&&<><p className="feature-info">Emojis aparecem nas mensagens como :nome:. Figurinhas são enviadas pelo seletor da conversa. Até 50 itens por comunidade.</p>{data.canManage&&<FeatureForm label="Adicionar à comunidade" onSubmit={async d=>{const file=d.get('file') as File;if(!file?.size)throw Error('Selecione uma imagem');if(file.size>2097152)throw Error('Máximo de 2 MB');const form=new FormData();form.append('file',file);const a=await api('/upload','POST',form);await api('/servers/'+server.id+'/assets','POST',{name:d.get('name'),kind:d.get('kind'),attachment_id:a.id});await load();await reload();setNotice('Item adicionado!');}}><label>Nome do item<input name="name" required pattern="[a-z0-9_]{2,24}" placeholder="gatinho_feliz" maxLength={24}/></label><label>Tipo<select name="kind" aria-label="Tipo do item"><option value="emoji">Emoji</option><option value="sticker">Figurinha</option></select></label><label>Imagem de até 2 MB<input name="file" type="file" accept="image/png,image/jpeg,image/gif,image/webp" required/></label></FeatureForm>}<div className="asset-grid">{data.assets.map((a:any)=><article key={a.id} className="feature-card"><img src={'/api/files/'+a.attachment_id} alt={a.name}/><strong>:{a.name}:</strong><small>{a.kind==='emoji'?'Emoji':'Figurinha'}</small>{data.canManage&&<button className="danger" disabled={busy} onClick={()=>void action(()=>api('/assets/'+a.id,'DELETE'),'Item removido. Mensagens antigas deixam de mostrar a imagem.')}>Remover {a.name}</button>}</article>)}</div></>}
 {tab==='channels'&&data.canManage&&<><p className="feature-info">Canais privados ficam visíveis apenas ao dono e aos cargos selecionados. O modo lento limita o intervalo entre mensagens de membros.</p>{data.channels.map((c:any)=><details className="feature-card" key={c.id}><summary>{c.private?'🔒':'#'} {c.name}</summary><FeatureForm key={JSON.stringify(c)} label={'Salvar canal '+c.name} onSubmit={async d=>{await api('/rooms/'+c.id+'/permissions','PATCH',{private:d.get('private')==='on',roles:d.getAll('roles'),slow_seconds:Number(d.get('slow_seconds'))});await load();await reload();setNotice('Permissões do canal atualizadas!');}}><label className="check"><input name="private" type="checkbox" defaultChecked={c.private}/>Canal privado</label><fieldset><legend>Cargos que podem acessar</legend>{data.roles.length?data.roles.map((role:any)=><label className="check" key={role.id}><input name="roles" value={role.id} type="checkbox" defaultChecked={c.roles.includes(role.id)}/>{role.name}</label>):<p>Crie cargos em Gerenciar comunidade. Sem cargos selecionados, só o dono acessa.</p>}</fieldset><label>Modo lento (segundos)<input name="slow_seconds" type="number" min={0} max={120} defaultValue={c.slow_seconds}/></label></FeatureForm></details>)}</>}
 {tab==='reports'&&data.canModerate&&<>{reports.length?reports.map(r=><article className="feature-card" key={r.id}><small>{r.status==='open'?'ABERTA':r.status==='resolved'?'RESOLVIDA':'DESCARTADA'} · {new Date(r.created_at).toLocaleString('pt-BR')}</small><h3>Mensagem de {r.display_name}</h3><blockquote>{r.deleted?'Mensagem apagada':r.body||'Anexo ou figurinha'}</blockquote><p>Motivo: {r.reason}</p>{r.status==='open'&&<div className="rsvp"><button disabled={busy} onClick={()=>void action(()=>api('/reports/'+r.id,'PATCH',{status:'resolved'}))}>Marcar resolvida</button><button disabled={busy} onClick={()=>void action(()=>api('/reports/'+r.id,'PATCH',{status:'dismissed'}))}>Descartar denúncia</button>{!r.deleted&&<button className="danger" disabled={busy} onClick={()=>void action(async()=>{await api('/messages/'+r.message_id,'DELETE');await api('/reports/'+r.id,'PATCH',{status:'resolved'});})}>Apagar mensagem denunciada</button>}</div>}</article>):<p className="empty">Nenhuma denúncia disponível para você.</p>}</>}
 </>}</div>;
}
