import {Children,cloneElement,isValidElement,useEffect,useRef,useState,type ReactNode,type PointerEvent} from 'react';
import {createPortal} from 'react-dom';
const mobile=()=>matchMedia('(max-width: 700px)').matches;
export function TouchMessage({children,className}:{children:ReactNode,className:string}){
 const [open,setOpen]=useState(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),start=useRef<{x:number,y:number}|null>(null),held=useRef(false),dialog=useRef<HTMLDialogElement>(null);
 const tools=Children.toArray(children).find(c=>isValidElement(c)&&(c.props as any).className==='message-tools') as any;
 const cancel=()=>{if(timer.current)clearTimeout(timer.current);timer.current=null;start.current=null;};
 useEffect(()=>()=>cancel(),[]);
 useEffect(()=>{if(open){dialog.current?.showModal();}else dialog.current?.close();},[open]);
 const down=(e:PointerEvent)=>{cancel();held.current=false;if(!tools||!mobile()||e.pointerType==='mouse'||!e.isPrimary||(e.target as Element).closest('button,input,textarea,select,audio,video'))return;start.current={x:e.clientX,y:e.clientY};timer.current=setTimeout(()=>{held.current=true;start.current=null;setOpen(true);window.getSelection()?.removeAllRanges();},480);};
 return <><article className={className+' touch-message'} onPointerDown={down} onPointerMove={e=>{if(start.current&&Math.hypot(e.clientX-start.current.x,e.clientY-start.current.y)>10)cancel();}} onPointerUp={cancel} onPointerCancel={cancel} onContextMenu={e=>{if(mobile()&&tools){e.preventDefault();cancel();held.current=true;setOpen(true);}}} onClickCapture={e=>{if(held.current){held.current=false;e.preventDefault();e.stopPropagation();}}}>{children}{tools&&<button className="mobile-message-more" aria-label="Opções da mensagem" onClick={()=>setOpen(true)}>···</button>}</article>{open&&createPortal(<dialog ref={dialog} className="message-sheet" aria-label="Opções da mensagem" onCancel={()=>setOpen(false)} onClose={()=>{held.current=false;setOpen(false);}} onClick={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div className="sheet-handle"/><header><h2>Mensagem</h2><button aria-label="Fechar opções" onClick={()=>setOpen(false)}>✕</button></header><div className="sheet-actions">{Children.map(tools?.props.children,(child:any)=>isValidElement<any>(child)?cloneElement(child as any,{onClick:(e:any)=>{held.current=false;setOpen(false);child.props.onClick?.(e);},children:<>{child.props.children}<span>{child.props.title}</span></>}):child)}</div><p>Segure uma mensagem para abrir estas opções.</p></dialog>,document.body)}</>;
}
export function useMobileSwipe(open:boolean,setOpen:(v:boolean)=>void){const start=useRef<{x:number,y:number,t:number}|null>(null),swiped=useRef(0);return {onClickCapture:(e:any)=>{if(Date.now()-swiped.current<600){e.preventDefault();e.stopPropagation();}},onPointerDown:(e:PointerEvent)=>{start.current=null;swiped.current=0;if(!mobile()||e.pointerType==='mouse'||!e.isPrimary||(e.target as Element).closest('input,textarea,select,audio,video,[role=dialog],dialog,.modal-backdrop,.call'))return;if(open||e.clientX<=44)start.current={x:e.clientX,y:e.clientY,t:Date.now()};},onPointerMove:(e:PointerEvent)=>{const s=start.current;if(!s)return;const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Math.abs(dy)>24&&Math.abs(dy)>Math.abs(dx)){start.current=null;return;}if(Date.now()-s.t<1000&&Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.8){start.current=null;if(!open&&dx>0){swiped.current=Date.now();setOpen(true);}else if(open&&dx<0){swiped.current=Date.now();setOpen(false);}}},onPointerUp:()=>{start.current=null;},onPointerCancel:()=>{start.current=null;}};}

