import {useEffect,useState} from 'react';
import {Check,Gift,Palette,Sparkles,X} from 'lucide-react';
import {api} from './api';
import {ProfileCard} from './ProfileSettings';
export default function Shop({me,reload}:{me:any,reload:()=>Promise<void>}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('shop'),[preview,setPreview]=useState<string|null>(me.equipped_frame),[confirm,setConfirm]=useState<any>(null),[notice,setNotice]=useState('');
 const load=async()=>setData(await api('/shop'));useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function action(fn:()=>Promise<any>,success:string){setBusy(true);setError('');try{await fn();await load();await reload();setNotice(success);setConfirm(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <div className="shop-page"><header className="shop-hero"><div><span className="eyebrow"><Sparkles size={13}/>PEQUENOS DETALHES. MUITO DE VOCÊ.</span><h1>Seu brilho, do seu jeito.</h1><p>Junte Faíscas e encontre uma moldura para chamar de sua.</p></div><div className="wallet"><Sparkles/><strong>{data?.sparks??me.sparks??0}</strong><span>Faíscas</span></div></header>
 <div className="daily-reward"><span className="daily-icon"><Gift size={25}/></span><div><strong>Um presente todo dia</strong><p>Resgate 100 Faíscas gratuitas. Sem anúncios, sem compra com dinheiro real.</p>{data&&!data.daily_available&&<small>Próximo resgate: {new Date(data.next_reset).toLocaleString('pt-BR')}</small>}</div><button className="primary" disabled={busy||!data?.daily_available} onClick={()=>void action(()=>api('/shop/daily','POST'),'Você ganhou 100 Faíscas!')}>{data?.daily_available?'Resgatar 100 Faíscas':'Resgatado hoje'}{data&&!data.daily_available&&<Check size={15}/>}</button></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="shop-notice" role="status"><Check size={15}/>{notice}</p>}
 <div className="shop-layout"><section><div className="tabs">{[['shop','Loja de molduras'],['owned','Minha coleção'],['ledger','Extrato']].map(([k,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{n}</button>)}</div>{!data?<p className="hint">Carregando sua coleção…</p>:tab==='ledger'?<div className="ledger">{data.ledger.length?data.ledger.map((l:any,i:number)=><div key={i}><span>{l.reason}<small>{new Date(l.created_at).toLocaleString('pt-BR')}</small></span><strong className={l.amount>0?'positive':''}>{l.amount>0?'+':''}{l.amount} ✦</strong></div>):<p>Seu extrato começa no primeiro resgate.</p>}</div>:<div className="frame-grid">{data.items.filter((i:any)=>tab!=='owned'||i.acquired_at).map((item:any)=><article key={item.id} className={'frame-product '+(preview===item.id?'selected':'')}><button className="frame-sample" aria-label={'Prévia '+item.name} onClick={()=>setPreview(item.id)} style={{'--item-color':item.color} as any}><span className={'sample-avatar frame-'+item.id}>{me.avatar_id?<img src={'/api/files/'+me.avatar_id} alt=""/>:me.display_name.slice(0,2).toUpperCase()}</span>{data.equipped_frame===item.id&&<span className="equipped-tag"><Check size={11}/>Em uso</span>}</button><div className="frame-description"><h3>{item.name}</h3><p>{item.description}</p><div><span className="frame-price"><Sparkles size={13}/>{item.price}</span>{item.acquired_at?<button disabled={busy||data.equipped_frame===item.id} onClick={()=>void action(()=>api('/shop/equip','POST',{item_id:item.id}),'Moldura equipada!')}>{data.equipped_frame===item.id?'Equipada':'Equipar'}</button>:<button className="primary" disabled={busy} onClick={()=>{setPreview(item.id);setConfirm(item);}}>Adquirir</button>}</div></div></article>)}{tab==='owned'&&!data.items.some((i:any)=>i.acquired_at)&&<div className="empty"><Palette size={32}/><h3>A coleção começa com uma escolha.</h3><p>Resgate suas Faíscas e visite a loja.</p></div>}</div>}</section><aside className="shop-preview"><span className="eyebrow">EXPERIMENTE ANTES DE ESCOLHER</span><ProfileCard user={{...me,equipped_frame:preview}} preview/><button onClick={()=>setPreview(null)}>Ver sem moldura</button>{data?.equipped_frame&&<button disabled={busy} onClick={()=>void action(()=>api('/shop/equip','POST',{item_id:null}),'Moldura removida. Ela continua na sua coleção.')}>Remover moldura equipada</button>}<p>As molduras aparecem no perfil, nos amigos e nas mensagens. Faíscas são virtuais, sem valor monetário.</p></aside></div>
 {confirm&&<div className="modal-backdrop"><section className="modal purchase-dialog" role="dialog" aria-modal="true" aria-label="Confirmar moldura"><header><h2>Levar {confirm.name}?</h2><button aria-label="Cancelar compra" onClick={()=>setConfirm(null)} disabled={busy}><X/></button></header><span className={'sample-avatar frame-'+confirm.id}>{me.display_name.slice(0,2).toUpperCase()}</span><p>Preço: <strong>{confirm.price} Faíscas</strong><br/>Seu saldo: {data.sparks} Faíscas</p><p>A moldura fica na sua coleção. Você pode equipar e remover quando quiser.</p><button className="primary" disabled={busy||data.sparks<confirm.price} onClick={()=>void action(()=>api('/shop/buy','POST',{item_id:confirm.id}),'Moldura adicionada à coleção! Clique em Equipar para usar.')}>{busy?'Adquirindo…':data.sparks<confirm.price?'Junte mais Faíscas':'Confirmar com Faíscas'}</button></section></div>}</div>;
}
