BEGIN;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS private boolean NOT NULL DEFAULT false;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS slow_seconds integer NOT NULL DEFAULT 0 CHECK(slow_seconds BETWEEN 0 AND 120);
ALTER TABLE server_members ADD COLUMN IF NOT EXISTS timeout_until timestamptz;
ALTER TABLE users ADD COLUMN IF NOT EXISTS theme text NOT NULL DEFAULT 'nexo';
ALTER TABLE users ADD COLUMN IF NOT EXISTS name_color text NOT NULL DEFAULT '#dce3f3';
ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_style text NOT NULL DEFAULT 'orbits';
CREATE TABLE IF NOT EXISTS room_roles(room_id uuid REFERENCES rooms ON DELETE CASCADE,role_id uuid REFERENCES roles ON DELETE CASCADE,PRIMARY KEY(room_id,role_id));
CREATE TABLE IF NOT EXISTS message_pins(message_id uuid PRIMARY KEY REFERENCES messages ON DELETE CASCADE,actor_id uuid REFERENCES users,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS favorites(user_id uuid REFERENCES users ON DELETE CASCADE,message_id uuid REFERENCES messages ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,message_id));
CREATE TABLE IF NOT EXISTS polls(message_id uuid PRIMARY KEY REFERENCES messages ON DELETE CASCADE,options jsonb NOT NULL,ends_at timestamptz NOT NULL,closed boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS poll_votes(message_id uuid REFERENCES polls ON DELETE CASCADE,user_id uuid REFERENCES users ON DELETE CASCADE,choice integer NOT NULL,PRIMARY KEY(message_id,user_id));
CREATE TABLE IF NOT EXISTS community_events(id uuid PRIMARY KEY,server_id uuid REFERENCES servers ON DELETE CASCADE,creator_id uuid REFERENCES users,title text NOT NULL,description text NOT NULL,starts_at timestamptz NOT NULL,cancelled boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS event_rsvps(event_id uuid REFERENCES community_events ON DELETE CASCADE,user_id uuid REFERENCES users ON DELETE CASCADE,response text NOT NULL CHECK(response IN ('going','maybe','declined')),PRIMARY KEY(event_id,user_id));
CREATE TABLE IF NOT EXISTS community_assets(id uuid PRIMARY KEY,server_id uuid REFERENCES servers ON DELETE CASCADE,creator_id uuid REFERENCES users,name text NOT NULL,kind text NOT NULL CHECK(kind IN ('emoji','sticker')),attachment_id uuid NOT NULL REFERENCES attachments,UNIQUE(server_id,name));
ALTER TABLE messages ADD COLUMN IF NOT EXISTS sticker_id uuid REFERENCES community_assets ON DELETE SET NULL;
CREATE TABLE IF NOT EXISTS reports(id uuid PRIMARY KEY,server_id uuid REFERENCES servers ON DELETE CASCADE,message_id uuid REFERENCES messages ON DELETE CASCADE,reporter_id uuid REFERENCES users,reason text NOT NULL,status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','resolved','dismissed')),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(message_id,reporter_id));
CREATE INDEX IF NOT EXISTS events_server_date ON community_events(server_id,starts_at);
CREATE INDEX IF NOT EXISTS reports_server ON reports(server_id,created_at DESC);
INSERT INTO migrations(version) VALUES(5) ON CONFLICT DO NOTHING;
COMMIT;
