import {z} from 'zod';
import {randomUUID as uid} from 'node:crypto';
import rateLimit from 'express-rate-limit';
import type {DB,QueryDb} from './db.js';
const id=z.string().uuid(),name=z.string().trim().min(1).max(80);
const fail=(status:number,message:string):never=>{throw Object.assign(new Error(message),{status});};
export async function guardSend(tx:QueryDb,user:string,room:any,body:string,moderator=false){
 await tx.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[user]);
 const [last]=await tx.query('SELECT body,created_at FROM messages WHERE user_id=$1 AND room_id=$2 ORDER BY created_at DESC LIMIT 1',[user,room.id]);if(!last)return;
 const elapsed=Date.now()-new Date(last.created_at).getTime();
 if(!moderator&&elapsed<room.slow_seconds*1000)fail(429,'Modo lento: aguarde '+Math.ceil(room.slow_seconds-elapsed/1000)+' segundo(s).');
 if(body.trim()&&last.body.trim().toLowerCase()===body.trim().toLowerCase()&&elapsed<15000)fail(429,'Evite repetir a mesma mensagem em sequência.');
}
export function communityFeatures(o:any){const {app,route,access,serverAccess,blocked,refresh,evictRoom}=o;const db:DB=o.db;
 const first=async(sql:string,args:any[]=[]) => (await db.query(sql,args))[0];
 const limited=rateLimit({windowMs:60_000,limit:45,keyGenerator:(req:any)=>req.user.id,message:{error:'Muitas ações. Aguarde um minuto.'}});
 async function message(user:string,mid:string,permission?:string){const m=await first('SELECT * FROM messages WHERE id=$1 AND NOT deleted',[id.parse(mid)]);if(!m)fail(404,'Mensagem não encontrada');const room=await access(user,m.room_id,permission);if(await blocked(user,m.user_id))fail(403,'Mensagem indisponível');return {m,room};}
 async function isModerator(user:string,room:any){if(!room.server_id)return room.owner_id===user;const s=await serverAccess(user,room.server_id);return s.owner_id===user||(s.permissions||[]).includes('manage_messages');}
 app.get('/api/rooms/:id/extras',route(async(req:any,res:any)=>{const room=await access(req.user.id,req.params.id);const rows=await db.query('SELECT p.*,m.user_id FROM polls p JOIN messages m ON m.id=p.message_id WHERE m.room_id=$1 AND NOT m.deleted',[room.id]);const polls=[];for(const p of rows){if(await blocked(req.user.id,p.user_id))continue;const votes=await db.query('SELECT choice,count(*)::int AS total FROM poll_votes WHERE message_id=$1 GROUP BY choice',[p.message_id]);const mine=await first('SELECT choice FROM poll_votes WHERE message_id=$1 AND user_id=$2',[p.message_id,req.user.id]);polls.push({...p,votes,choice:mine?.choice??null});}
 const pins=[];for(const m of await db.query('SELECT m.*,u.display_name FROM message_pins p JOIN messages m ON m.id=p.message_id JOIN users u ON u.id=m.user_id WHERE m.room_id=$1 AND NOT m.deleted ORDER BY p.created_at DESC',[room.id]))if(!await blocked(req.user.id,m.user_id))pins.push(m);
 const favorites=await db.query('SELECT f.message_id FROM favorites f JOIN messages m ON m.id=f.message_id WHERE m.room_id=$1 AND f.user_id=$2',[room.id,req.user.id]);res.json({polls,pins,favorites:favorites.map(f=>f.message_id),assets:room.server_id?await db.query('SELECT * FROM community_assets WHERE server_id=$1 ORDER BY name',[room.server_id]):[],can_pin:await isModerator(req.user.id,room)});}));
 app.post('/api/rooms/:id/polls',limited,route(async(req:any,res:any)=>{const room=await access(req.user.id,req.params.id,'send');if(room.kind==='forum')fail(400,'Crie um assunto no fórum ou uma enquete em um canal de texto');const x=z.object({question:name,options:z.array(z.string().trim().min(1).max(80)).min(2).max(8).refine(a=>new Set(a.map(x=>x.toLowerCase())).size===a.length,'Use opções diferentes'),hours:z.number().int().min(1).max(168)}).strict().parse(req.body);const mid=uid(),moderator=await isModerator(req.user.id,room);await db.transaction(async tx=>{await guardSend(tx,req.user.id,room,x.question,moderator);await tx.query('INSERT INTO messages(id,room_id,user_id,body) VALUES($1,$2,$3,$4)',[mid,room.id,req.user.id,x.question]);await tx.query('INSERT INTO polls(message_id,options,ends_at) VALUES($1,$2,$3)',[mid,JSON.stringify(x.options),new Date(Date.now()+x.hours*3600000)]);});refresh();res.json({id:mid});}));
 app.post('/api/polls/:id/vote',limited,route(async(req:any,res:any)=>{await message(req.user.id,req.params.id,'send');const choice=z.number().int().min(0).max(7).nullable().parse(req.body.choice);await db.transaction(async tx=>{const [p]=await tx.query('SELECT * FROM polls WHERE message_id=$1 FOR UPDATE',[req.params.id]);if(!p)fail(404,'Enquete não encontrada');if(p.closed||new Date(p.ends_at).getTime()<=Date.now())fail(409,'Enquete encerrada');if(choice!==null&&choice>=p.options.length)fail(400,'Opção inválida');if(choice===null)await tx.query('DELETE FROM poll_votes WHERE message_id=$1 AND user_id=$2',[req.params.id,req.user.id]);else await tx.query('INSERT INTO poll_votes(message_id,user_id,choice) VALUES($1,$2,$3) ON CONFLICT(message_id,user_id) DO UPDATE SET choice=$3',[req.params.id,req.user.id,choice]);});refresh();res.json({ok:true});}));
 app.post('/api/polls/:id/close',route(async(req:any,res:any)=>{const {m,room}=await message(req.user.id,req.params.id,'send');if(m.user_id!==req.user.id&&!await isModerator(req.user.id,room))fail(403,'Somente autor ou moderador pode encerrar');await db.query('UPDATE polls SET closed=true WHERE message_id=$1',[m.id]);refresh();res.json({ok:true});}));
 app.post('/api/messages/:id/pin',limited,route(async(req:any,res:any)=>{const {m,room}=await message(req.user.id,req.params.id,'manage_messages');const enabled=z.boolean().parse(req.body.enabled);await db.transaction(async tx=>{await tx.query('SELECT id FROM rooms WHERE id=$1 FOR UPDATE',[room.id]);if(enabled){const [n]=await tx.query('SELECT count(*)::int AS n FROM message_pins p JOIN messages m ON m.id=p.message_id WHERE m.room_id=$1 AND NOT m.deleted',[room.id]);if(n.n>=30)fail(400,'Até 30 mensagens fixadas por conversa');await tx.query('INSERT INTO message_pins(message_id,actor_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[m.id,req.user.id]);}else await tx.query('DELETE FROM message_pins WHERE message_id=$1',[m.id]);});refresh();res.json({ok:true});}));
 app.post('/api/messages/:id/favorite',limited,route(async(req:any,res:any)=>{const {m}=await message(req.user.id,req.params.id);if(z.boolean().parse(req.body.enabled))await db.query('INSERT INTO favorites(user_id,message_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,m.id]);else await db.query('DELETE FROM favorites WHERE user_id=$1 AND message_id=$2',[req.user.id,m.id]);refresh();res.json({ok:true});}));
 app.get('/api/favorites',route(async(req:any,res:any)=>{const rows=await db.query('SELECT m.*,r.name AS room_name,u.display_name FROM favorites f JOIN messages m ON m.id=f.message_id JOIN rooms r ON r.id=m.room_id JOIN users u ON u.id=m.user_id WHERE f.user_id=$1 AND NOT m.deleted ORDER BY f.created_at DESC LIMIT 100',[req.user.id]);const result=[];for(const m of rows)try{await access(req.user.id,m.room_id);if(!await blocked(req.user.id,m.user_id))result.push(m);}catch(e:any){if(![403,404].includes(e.status))throw e;}res.json(result);}));
 app.get('/api/servers/:id/hub',route(async(req:any,res:any)=>{const s=await serverAccess(req.user.id,req.params.id);const events=await db.query('SELECT e.*,u.display_name FROM community_events e JOIN users u ON u.id=e.creator_id WHERE e.server_id=$1 ORDER BY e.starts_at DESC LIMIT 60',[s.id]);for(const e of events)e.attendees=await db.query('SELECT r.user_id,r.response,u.display_name FROM event_rsvps r JOIN users u ON u.id=r.user_id JOIN server_members sm ON sm.user_id=r.user_id AND sm.server_id=$2 WHERE r.event_id=$1 AND NOT sm.banned',[e.id,s.id]);const canManage=s.owner_id===req.user.id||(s.permissions||[]).includes('manage_channels'),canModerate=s.owner_id===req.user.id||(s.permissions||[]).includes('manage_messages');const channels=canManage?await db.query("SELECT r.*,COALESCE((SELECT jsonb_agg(role_id) FROM room_roles WHERE room_id=r.id),'[]') AS roles FROM rooms r WHERE r.server_id=$1",[s.id]):[];res.json({events,channels,assets:await db.query('SELECT * FROM community_assets WHERE server_id=$1 ORDER BY name',[s.id]),roles:await db.query('SELECT id,name FROM roles WHERE server_id=$1',[s.id]),canManage,canModerate,canCreate:s.owner_id===req.user.id||(s.permissions||['send']).includes('send')});}));
 const eventInput=z.object({title:name,description:z.string().trim().max(1000),starts_at:z.iso.datetime({offset:true})}).strict();
 app.post('/api/servers/:id/events',limited,route(async(req:any,res:any)=>{const s=await serverAccess(req.user.id,req.params.id,'send'),x=eventInput.parse(req.body);if(new Date(x.starts_at).getTime()<Date.now())fail(400,'Escolha um horário futuro');const eid=uid();await db.query('INSERT INTO community_events(id,server_id,creator_id,title,description,starts_at) VALUES($1,$2,$3,$4,$5,$6)',[eid,s.id,req.user.id,x.title,x.description,x.starts_at]);refresh();res.json({id:eid});}));
 app.patch('/api/events/:id',limited,route(async(req:any,res:any)=>{const e=await first('SELECT * FROM community_events WHERE id=$1',[id.parse(req.params.id)]);if(!e)fail(404,'Evento não encontrado');await serverAccess(req.user.id,e.server_id,e.creator_id===req.user.id?'send':'manage_channels');const x=eventInput.extend({cancelled:z.boolean()}).parse(req.body);if(!x.cancelled&&new Date(x.starts_at).getTime()<Date.now())fail(400,'Escolha um horário futuro');await db.query('UPDATE community_events SET title=$2,description=$3,starts_at=$4,cancelled=$5 WHERE id=$1',[e.id,x.title,x.description,x.starts_at,x.cancelled]);refresh();res.json({ok:true});}));
 app.post('/api/events/:id/rsvp',limited,route(async(req:any,res:any)=>{const e=await first('SELECT * FROM community_events WHERE id=$1',[id.parse(req.params.id)]);if(!e)fail(404,'Evento não encontrado');await serverAccess(req.user.id,e.server_id,'send');if(e.cancelled||new Date(e.starts_at).getTime()<Date.now())fail(409,'Evento encerrado ou cancelado');const response=z.enum(['going','maybe','declined']).parse(req.body.response);await db.query('INSERT INTO event_rsvps(event_id,user_id,response) VALUES($1,$2,$3) ON CONFLICT(event_id,user_id) DO UPDATE SET response=$3',[e.id,req.user.id,response]);refresh();res.json({ok:true});}));
 app.post('/api/servers/:id/assets',limited,route(async(req:any,res:any)=>{const s=await serverAccess(req.user.id,req.params.id,'manage_channels');const x=z.object({name:z.string().regex(/^[a-z0-9_]{2,24}$/),kind:z.enum(['emoji','sticker']),attachment_id:id}).strict().parse(req.body);const a=await first('SELECT * FROM attachments WHERE id=$1 AND owner_id=$2 AND room_id IS NULL',[x.attachment_id,req.user.id]);if(!a||!a.mime.startsWith('image/')||a.size>2097152)fail(400,'Envie uma imagem própria de até 2 MB');const aid=uid();await db.transaction(async tx=>{await tx.query('SELECT id FROM servers WHERE id=$1 FOR UPDATE',[s.id]);const [cap]=await tx.query('SELECT count(*)::int AS total FROM community_assets WHERE server_id=$1',[s.id]);if(cap.total>=50)fail(400,'Até 50 emojis e figurinhas por comunidade');await tx.query('INSERT INTO community_assets(id,server_id,creator_id,name,kind,attachment_id) VALUES($1,$2,$3,$4,$5,$6)',[aid,s.id,req.user.id,x.name,x.kind,x.attachment_id]);});refresh();res.json({id:aid});}));
 app.delete('/api/assets/:id',route(async(req:any,res:any)=>{const a=await first('SELECT * FROM community_assets WHERE id=$1',[id.parse(req.params.id)]);if(!a)fail(404,'Item não encontrado');await serverAccess(req.user.id,a.server_id,'manage_channels');await db.query('DELETE FROM community_assets WHERE id=$1',[a.id]);refresh();res.json({ok:true});}));
 app.patch('/api/rooms/:id/permissions',limited,route(async(req:any,res:any)=>{const room=await first('SELECT * FROM rooms WHERE id=$1',[id.parse(req.params.id)]);if(!room?.server_id)fail(400,'Use um canal de comunidade');await serverAccess(req.user.id,room.server_id,'manage_channels');const x=z.object({private:z.boolean(),roles:z.array(id).max(30),slow_seconds:z.number().int().min(0).max(120)}).strict().parse(req.body);for(const rid of x.roles)if(!await first('SELECT 1 FROM roles WHERE id=$1 AND server_id=$2',[rid,room.server_id]))fail(400,'Cargo de outra comunidade');await db.transaction(async tx=>{await tx.query('UPDATE rooms SET private=$2,slow_seconds=$3 WHERE id=$1',[room.id,x.private,x.slow_seconds]);await tx.query('DELETE FROM room_roles WHERE room_id=$1',[room.id]);for(const rid of new Set(x.roles))await tx.query('INSERT INTO room_roles(room_id,role_id) VALUES($1,$2)',[room.id,rid]);});await evictRoom(room.id);refresh();res.json({ok:true});}));
 app.post('/api/messages/:id/report',limited,route(async(req:any,res:any)=>{const {m,room}=await message(req.user.id,req.params.id);if(!room.server_id)fail(400,'Denúncias são moderadas pela comunidade. Em DMs, use Bloquear.');if(m.user_id===req.user.id)fail(400,'Você não pode denunciar sua própria mensagem');const reason=z.string().trim().min(5).max(500).parse(req.body.reason);await db.query('INSERT INTO reports(id,server_id,message_id,reporter_id,reason) VALUES($1,$2,$3,$4,$5) ON CONFLICT(message_id,reporter_id) DO NOTHING',[uid(),room.server_id,m.id,req.user.id,reason]);res.json({ok:true});}));
 app.get('/api/servers/:id/reports',route(async(req:any,res:any)=>{await serverAccess(req.user.id,req.params.id,'manage_messages');const rows=await db.query('SELECT r.*,m.body,m.room_id,m.user_id,m.deleted,u.display_name FROM reports r JOIN messages m ON m.id=r.message_id JOIN users u ON u.id=m.user_id WHERE r.server_id=$1 ORDER BY r.created_at DESC LIMIT 100',[req.params.id]);const visible=[];for(const r of rows)try{await access(req.user.id,r.room_id);visible.push(r);}catch(e:any){if(![403,404].includes(e.status))throw e;}res.json(visible);}));
 app.patch('/api/reports/:id',route(async(req:any,res:any)=>{const r=await first('SELECT r.*,m.room_id FROM reports r JOIN messages m ON m.id=r.message_id WHERE r.id=$1',[id.parse(req.params.id)]);if(!r)fail(404,'Denúncia não encontrada');await access(req.user.id,r.room_id,'manage_messages');const status=z.enum(['resolved','dismissed']).parse(req.body.status);await db.query('UPDATE reports SET status=$2 WHERE id=$1',[r.id,status]);await db.query('INSERT INTO audit(id,server_id,actor_id,action) VALUES($1,$2,$3,$4)',[uid(),r.server_id,req.user.id,'report_'+status+': '+r.id]);refresh();res.json({ok:true});}));
 app.post('/api/servers/:id/timeout/:user',limited,route(async(req:any,res:any)=>{const s=await serverAccess(req.user.id,req.params.id,'manage_members'),target=id.parse(req.params.user),minutes=z.number().int().min(0).max(10080).parse(req.body.minutes);const m=await first('SELECT * FROM server_members WHERE server_id=$1 AND user_id=$2',[s.id,target]);if(!m||target===s.owner_id||target===req.user.id||(s.owner_id!==req.user.id&&m.role_id))fail(403,'Você não pode moderar este membro');await db.query('UPDATE server_members SET timeout_until=$3 WHERE server_id=$1 AND user_id=$2',[s.id,target,minutes?new Date(Date.now()+minutes*60000):null]);for(const r of await db.query('SELECT id FROM rooms WHERE server_id=$1',[s.id]))await evictRoom(r.id,target);await db.query('INSERT INTO audit(id,server_id,actor_id,action) VALUES($1,$2,$3,$4)',[uid(),s.id,req.user.id,'timeout '+minutes+'m: '+target]);refresh();res.json({ok:true});}));
}
