import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {guardSend} from './community-features.js';
import type {QueryDb} from './db.js';
const id=z.string().uuid(),body=z.string().trim().min(1).max(4000);
const fail=(status:number,message:string):never=>{throw Object.assign(new Error(message),{status});};
export function everydayFeatures({app,db,route,access,serverAccess,blocked,refresh,notify,members}:any){
 app.get('/api/invites/:code',route(async(req:any,res:any)=>{const code=z.string().min(1).max(64).parse(req.params.code);const [inv]=await db.query('SELECT s.name FROM invites i JOIN servers s ON s.id=i.server_id WHERE i.code=$1 AND i.expires_at>now() AND i.uses<i.max_uses',[code]);if(!inv)fail(404,'Convite expirado ou inválido');res.json(inv);}));
 app.patch('/api/accessibility',route(async(req:any,res:any)=>{const x=z.object({font_size:z.number().int().min(14).max(22),contrast:z.boolean(),reduce_motion:z.boolean()}).strict().parse(req.body);await db.query('UPDATE users SET accessibility=$2 WHERE id=$1',[req.user.id,JSON.stringify(x)]);refresh();res.json(x);}));
 app.get('/api/search',route(async(req:any,res:any)=>{const x=z.object({q:z.string().trim().max(200).default(''),room:id.optional(),person:z.string().max(24).optional(),from:z.iso.datetime({offset:true}).optional(),until:z.iso.datetime({offset:true}).optional(),cursor:id.optional()}).parse(req.query);const candidates=await db.query('SELECT DISTINCT r.id FROM rooms r LEFT JOIN room_members rm ON rm.room_id=r.id LEFT JOIN server_members sm ON sm.server_id=r.server_id WHERE (rm.user_id=$1 AND r.server_id IS NULL OR sm.user_id=$1 AND NOT sm.banned)',[req.user.id]);const allowed:string[]=[];for(const r of candidates)if(!x.room||r.id===x.room)try{await access(req.user.id,r.id);allowed.push(r.id);}catch(e:any){if(![403,404].includes(e.status))throw e;}
 const rows=await db.query(`SELECT m.*,u.username,u.display_name,r.name AS room_name FROM messages m JOIN users u ON u.id=m.user_id JOIN rooms r ON r.id=m.room_id WHERE m.room_id=ANY($1::uuid[]) AND NOT m.deleted AND position(lower($2) in lower(m.body))>0 AND ($3::text IS NULL OR u.username=$3) AND ($4::timestamptz IS NULL OR m.created_at>=$4) AND ($5::timestamptz IS NULL OR m.created_at<=$5) AND ($6::uuid IS NULL OR (m.created_at,m.id)<(SELECT created_at,id FROM messages WHERE id=$6)) AND NOT EXISTS(SELECT 1 FROM relations b WHERE b.state='blocked' AND (b.sender=$7 AND b.recipient=m.user_id OR b.recipient=$7 AND b.sender=m.user_id)) ORDER BY m.created_at DESC,m.id DESC LIMIT 51`,[allowed,x.q,x.person?.replace(/^@/,'').toLowerCase()||null,x.from||null,x.until||null,x.cursor||null,req.user.id]);res.json({messages:rows.slice(0,50),next:rows.length>50?rows[49].id:null});}));
 app.get('/api/servers/:id/profile',route(async(req:any,res:any)=>{await serverAccess(req.user.id,String(req.params.id));res.json((await db.query('SELECT nickname,bio,avatar_id FROM server_members WHERE server_id=$1 AND user_id=$2',[req.params.id,req.user.id]))[0]);}));
 app.patch('/api/servers/:id/profile',route(async(req:any,res:any)=>{await serverAccess(req.user.id,String(req.params.id));const x=z.object({nickname:z.string().trim().max(50),bio:z.string().max(300),avatar_id:id.nullable()}).strict().parse(req.body);if(x.avatar_id&&!(await db.query("SELECT 1 FROM attachments WHERE id=$1 AND owner_id=$2 AND room_id IS NULL AND mime LIKE 'image/%'",[x.avatar_id,req.user.id])).length)fail(400,'Avatar inválido');await db.query('UPDATE server_members SET nickname=$3,bio=$4,avatar_id=$5 WHERE server_id=$1 AND user_id=$2',[req.params.id,req.user.id,x.nickname,x.bio,x.avatar_id]);refresh();res.json({ok:true});}));
 async function root(user:string,mid:string,permission?:string){const [m]=await db.query('SELECT * FROM messages WHERE id=$1 AND NOT deleted',[id.parse(mid)]);if(!m)fail(404,'Mensagem não encontrada');const room=await access(user,m.room_id,permission);if(await blocked(user,m.user_id))fail(403,'Mensagem indisponível');return {m,room};}
 app.post('/api/messages/:id/thread',route(async(req:any,res:any)=>{const {m}=await root(req.user.id,req.params.id,'send');if(m.thread_id)fail(400,'Abra o tópico original.');const title=z.string().trim().min(1).max(80).parse(req.body.title);await db.query('INSERT INTO threads(id,title) VALUES($1,$2) ON CONFLICT DO NOTHING',[m.id,title]);refresh();res.json({id:m.id});}));
 app.get('/api/threads/:id',route(async(req:any,res:any)=>{await root(req.user.id,req.params.id);const [t]=await db.query('SELECT * FROM threads WHERE id=$1',[req.params.id]);if(!t)fail(404,'Tópico não encontrado');const rows=await db.query(`SELECT m.*,u.display_name,u.username FROM messages m JOIN users u ON u.id=m.user_id WHERE m.thread_id=$1 AND NOT EXISTS(SELECT 1 FROM relations b WHERE b.state='blocked' AND (b.sender=$2 AND b.recipient=m.user_id OR b.recipient=$2 AND b.sender=m.user_id)) ORDER BY m.created_at,m.id LIMIT 200`,[t.id,req.user.id]);res.json({...t,messages:rows});}));
 app.patch('/api/threads/:id',route(async(req:any,res:any)=>{const {m}=await root(req.user.id,req.params.id);if(m.user_id!==req.user.id)await access(req.user.id,m.room_id,'manage_messages');const closed=z.boolean().parse(req.body.closed);await db.query('UPDATE threads SET closed=$2 WHERE id=$1',[m.id,closed]);refresh();res.json({ok:true});}));
 app.post('/api/threads/:id/messages',route(async(req:any,res:any)=>{const {m,room}=await root(req.user.id,req.params.id,'send');const text=body.parse(req.body.body);const perm=room.server_id?await serverAccess(req.user.id,room.server_id):null;const mid=randomUUID();await db.transaction(async(tx:QueryDb)=>{const [t]=await tx.query('SELECT * FROM threads WHERE id=$1 FOR UPDATE',[m.id]);if(!t||t.closed)fail(409,'Tópico encerrado');if(Number((await tx.query('SELECT count(*) AS n FROM messages WHERE thread_id=$1',[m.id]))[0].n)>=200)fail(400,'Limite de 200 respostas por tópico nesta versão.');await guardSend(tx,req.user.id,room,text,room.server_id?(perm?.owner_id===req.user.id||perm?.permissions?.includes('manage_messages')):room.owner_id===req.user.id);await tx.query('INSERT INTO messages(id,room_id,user_id,body,thread_id) VALUES($1,$2,$3,$4,$5)',[mid,room.id,req.user.id,text,m.id]);});await notify(m.user_id,req.user.id,req.user.display_name+' respondeu ao seu tópico',room.id);refresh();res.json({id:mid});}));
 app.get('/api/scheduled',route(async(req:any,res:any)=>res.json(await db.query('SELECT s.*,r.name AS room_name FROM scheduled_messages s JOIN rooms r ON r.id=s.room_id WHERE s.user_id=$1 ORDER BY s.send_at DESC LIMIT 100',[req.user.id]))));
 app.post('/api/rooms/:id/scheduled',route(async(req:any,res:any)=>{const room=await access(req.user.id,req.params.id,'send');if(room.kind==='forum')fail(400,'Agende em um canal de texto; o fórum organiza assuntos.');const x=z.object({body,send_at:z.iso.datetime({offset:true})}).parse(req.body);const date=new Date(x.send_at).getTime();if(date<Date.now()+30000||date>Date.now()+30*86400000)fail(400,'Escolha entre 30 segundos e 30 dias no futuro.');const sid=randomUUID();await db.transaction(async(tx:QueryDb)=>{await tx.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[req.user.id]);if(Number((await tx.query("SELECT count(*) n FROM scheduled_messages WHERE user_id=$1 AND status='pending'",[req.user.id]))[0].n)>=20)fail(400,'Limite de 20 mensagens pendentes');await tx.query('INSERT INTO scheduled_messages(id,user_id,room_id,body,send_at) VALUES($1,$2,$3,$4,$5)',[sid,req.user.id,room.id,x.body,x.send_at]);});res.json({id:sid});}));
 app.delete('/api/scheduled/:id',route(async(req:any,res:any)=>{const rows=await db.query("UPDATE scheduled_messages SET status='cancelled' WHERE id=$1 AND user_id=$2 AND status='pending' RETURNING id",[id.parse(req.params.id),req.user.id]);if(!rows.length)fail(409,'Mensagem já enviada, cancelada ou indisponível.');res.json({ok:true});}));
 const week="date_trunc('week',now() AT TIME ZONE 'UTC')::date";
 async function quests(tx:QueryDb,user:string){const [p]=await tx.query(`SELECT (SELECT count(*)::int FROM daily_rewards WHERE user_id=$1 AND reward_day>=${week}) AS visits,(SELECT count(*)::int FROM favorites WHERE user_id=$1 AND created_at>=${week}::timestamp AT TIME ZONE 'UTC') AS saved,(SELECT count(*)::int FROM event_rsvps e JOIN community_events c ON c.id=e.event_id WHERE e.user_id=$1 AND e.response='going' AND NOT c.cancelled AND c.starts_at>=${week}::timestamp AT TIME ZONE 'UTC' AND c.starts_at<(${week}+7)::timestamp AT TIME ZONE 'UTC') AS events`,[user]);const claims=await tx.query(`SELECT quest FROM weekly_claims WHERE user_id=$1 AND week=${week}`,[user]);return [{id:'visits',name:'Encontre sua turma em 3 dias',hint:'Resgate o presente diário em três dias desta semana.',goal:3,progress:p.visits,reward:80},{id:'saved',name:'Guarde uma boa conversa',hint:'Favorite uma mensagem nesta semana.',goal:1,progress:p.saved,reward:30},{id:'events',name:'Combine um encontro',hint:'Confirme presença em um evento desta semana.',goal:1,progress:p.events,reward:40}].map(q=>({...q,claimed:claims.some(c=>c.quest===q.id)}));}
 app.get('/api/quests',route(async(req:any,res:any)=>res.json({quests:await quests(db,req.user.id),reset:(await db.query(`SELECT (${week}+7)::text AS day`))[0].day})));
 app.post('/api/quests/:id/claim',route(async(req:any,res:any)=>{const result=await db.transaction(async(tx:QueryDb)=>{await tx.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[req.user.id]);const q=(await quests(tx,req.user.id)).find(q=>q.id===req.params.id);if(!q||q.claimed||q.progress<q.goal)fail(409,'Missão incompleta ou já resgatada');await tx.query(`INSERT INTO weekly_claims(user_id,week,quest) VALUES($1,${week},$2)`,[req.user.id,q!.id]);await tx.query('INSERT INTO wallet_ledger(id,user_id,amount,reason) VALUES($1,$2,$3,$4)',[randomUUID(),req.user.id,q!.reward,'Missão semanal: '+q!.name]);return (await tx.query('UPDATE users SET sparks=sparks+$2 WHERE id=$1 RETURNING sparks',[req.user.id,q!.reward]))[0];});refresh();res.json(result);}));
 let running:Promise<void>|null=null;
 async function deliver(){for(const s of await db.query("SELECT * FROM scheduled_messages WHERE status='pending' AND send_at<=now() ORDER BY send_at LIMIT 20")){try{const room=await access(s.user_id,s.room_id,'send'),perm=room.server_id?await serverAccess(s.user_id,room.server_id):null;const sent=await db.transaction(async(tx:QueryDb)=>{const [current]=await tx.query('SELECT status FROM scheduled_messages WHERE id=$1 FOR UPDATE',[s.id]);if(current?.status!=='pending')return false;await guardSend(tx,s.user_id,room,s.body,room.server_id?(perm?.owner_id===s.user_id||perm?.permissions?.includes('manage_messages')):room.owner_id===s.user_id);await tx.query('INSERT INTO messages(id,room_id,user_id,body) VALUES($1,$2,$3,$4)',[s.id,s.room_id,s.user_id,s.body]);await tx.query("UPDATE scheduled_messages SET status='sent' WHERE id=$1",[s.id]);return true;});if(sent){for(const m of await members(room)){const [u]=await db.query('SELECT username FROM users WHERE id=$1',[m.user_id]);const [prefs]=await db.query('SELECT muted FROM room_members WHERE room_id=$1 AND user_id=$2',[room.id,m.user_id]);await notify(m.user_id,s.user_id,s.body.slice(0,100),room.id,new RegExp('(^|\\s)@'+u.username+'(?=\\s|$|[.,!?])').test(s.body));}refresh();}}catch(e:any){if(e.status&&e.status<500){await db.query("UPDATE scheduled_messages SET status='failed',error=$2 WHERE id=$1 AND status='pending'",[s.id,'Envio indisponível. Confira o acesso à conversa e o modo lento.']);refresh();}else console.error('Falha ao enviar agendamento',e);}}}
 const tick=()=>running??(running=deliver().finally(()=>{running=null;}));const timer=setInterval(()=>void tick().catch(console.error),5000);timer.unref();return {tick,close:async()=>{clearInterval(timer);await running;}};
}
