import type {DB} from './db.js';
import {randomUUID} from 'node:crypto';
function fail(status:number,message:string):never{throw Object.assign(new Error(message),{status});}
export function shopService(db:DB){return {
 async view(user:string){const [wallet]=await db.query('SELECT sparks,equipped_frame,equipped_background,equipped_color,equipped_effect FROM users WHERE id=$1',[user]);const items=await db.query('SELECT s.*,i.acquired_at FROM shop_items s LEFT JOIN inventory i ON i.item_id=s.id AND i.user_id=$1 ORDER BY s.price',[user]);const claimed=await db.query("SELECT 1 FROM daily_rewards WHERE user_id=$1 AND reward_day=(now() AT TIME ZONE 'UTC')::date",[user]);const ledger=await db.query('SELECT amount,reason,created_at FROM wallet_ledger WHERE user_id=$1 ORDER BY created_at DESC LIMIT 20',[user]);return {...wallet,items,ledger,daily_available:!claimed.length,daily_amount:100,next_reset:new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),new Date().getUTCDate()+1)).toISOString()};},
 async daily(user:string){return db.transaction(async tx=>{
  await tx.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[user]);
  const claimed=await tx.query("INSERT INTO daily_rewards(user_id,reward_day) VALUES($1,(now() AT TIME ZONE 'UTC')::date) ON CONFLICT DO NOTHING RETURNING user_id",[user]);if(!claimed.length)fail(409,'Você já resgatou as Faíscas de hoje.');
  const [wallet]=await tx.query('UPDATE users SET sparks=sparks+100 WHERE id=$1 RETURNING sparks',[user]);await tx.query('INSERT INTO wallet_ledger(id,user_id,amount,reason) VALUES($1,$2,100,$3)',[randomUUID(),user,'Presente diário']);return wallet;
 });},
 async buy(user:string,item:string){return db.transaction(async tx=>{
  await tx.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[user]);
  const [product]=await tx.query('SELECT * FROM shop_items WHERE id=$1',[item]);if(!product)fail(404,'Moldura não encontrada');if((await tx.query('SELECT 1 FROM inventory WHERE user_id=$1 AND item_id=$2',[user,item])).length)fail(409,'Você já tem esse item');
  const [wallet]=await tx.query('UPDATE users SET sparks=sparks-$2 WHERE id=$1 AND sparks>=$2 RETURNING sparks',[user,product.price]);if(!wallet)fail(400,'Faíscas insuficientes. Resgate o presente diário para juntar mais.');
  await tx.query('INSERT INTO inventory(user_id,item_id) VALUES($1,$2)',[user,item]);await tx.query('INSERT INTO wallet_ledger(id,user_id,amount,reason) VALUES($1,$2,$3,$4)',[randomUUID(),user,-product.price,'Item: '+product.name]);return wallet;
 });},
 async equip(user:string,item:string|null,kind='frame'){const columns:Record<string,string>={frame:'equipped_frame',background:'equipped_background',color:'equipped_color',effect:'equipped_effect'};if(!columns[kind])fail(400,'Categoria inválida');if(item&&!(await db.query('SELECT 1 FROM inventory i JOIN shop_items s ON s.id=i.item_id WHERE i.user_id=$1 AND i.item_id=$2 AND s.kind=$3',[user,item,kind])).length)fail(403,'Adquira um item desta categoria antes de equipar');await db.query('UPDATE users SET '+columns[kind]+'=$2 WHERE id=$1',[user,item]);return {ok:true};},
 async gift(user:string,username:string,item:string){return db.transaction(async tx=>{const [recipient]=await tx.query('SELECT id,display_name FROM users WHERE username=$1',[username]);if(!recipient||recipient.id===user)fail(400,'Escolha um amigo');await tx.query('SELECT id FROM users WHERE id=ANY($1::uuid[]) ORDER BY id FOR UPDATE',[[user,recipient.id]]);if(!(await tx.query("SELECT 1 FROM relations WHERE state='accepted' AND (sender=$1 AND recipient=$2 OR sender=$2 AND recipient=$1)",[user,recipient.id])).length||(await tx.query("SELECT 1 FROM relations WHERE state='blocked' AND (sender=$1 AND recipient=$2 OR sender=$2 AND recipient=$1)",[user,recipient.id])).length)fail(403,'Presentes são permitidos somente entre amigos sem bloqueio');if(Number((await tx.query("SELECT count(*) n FROM shop_gifts WHERE sender_id=$1 AND created_at>now()-interval '1 day'",[user]))[0].n)>=20)fail(429,'Até 20 presentes por dia');const [product]=await tx.query('SELECT * FROM shop_items WHERE id=$1',[item]);if(!product)fail(404,'Item não encontrado');if((await tx.query('SELECT 1 FROM inventory WHERE user_id=$1 AND item_id=$2',[recipient.id,item])).length)fail(409,'Seu amigo já tem esse item. Nenhuma Faísca foi descontada.');const [wallet]=await tx.query('UPDATE users SET sparks=sparks-$2 WHERE id=$1 AND sparks>=$2 RETURNING sparks',[user,product.price]);if(!wallet)fail(400,'Faíscas insuficientes');await tx.query('INSERT INTO inventory(user_id,item_id) VALUES($1,$2)',[recipient.id,item]);await tx.query('INSERT INTO shop_gifts(id,sender_id,recipient_id,item_id) VALUES($1,$2,$3,$4)',[randomUUID(),user,recipient.id,item]);await tx.query('INSERT INTO wallet_ledger(id,user_id,amount,reason) VALUES($1,$2,$3,$4)',[randomUUID(),user,-product.price,'Presente para @'+username+': '+product.name]);const [sender]=await tx.query('SELECT display_name FROM users WHERE id=$1',[user]);await tx.query('INSERT INTO notifications(id,user_id,actor_id,body) VALUES($1,$2,$3,$4)',[randomUUID(),recipient.id,user,sender.display_name+' presenteou você com '+product.name+'. Abra sua coleção na loja.']);return wallet;});}

};}
