BEGIN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_id uuid REFERENCES attachments(id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS accent_color text NOT NULL DEFAULT '#b2a1ff';
ALTER TABLE users ADD COLUMN IF NOT EXISTS pronouns text NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS custom_status text NOT NULL DEFAULT '';
INSERT INTO migrations(version) VALUES(2) ON CONFLICT DO NOTHING;
COMMIT;
