import {useEffect,useRef,useState} from 'react';
import {Headphones,Phone,PhoneMissed,PhoneOff,X} from 'lucide-react';
import type {Socket} from 'socket.io-client';
import {api} from './api';
const labels:Record<string,string>={accepted:'Chamada aceita',declined:'Chamada recusada',missed:'Chamada não atendida',cancelled:'Chamada cancelada',busy:'Pessoa ocupada',ringing:'Chamando'};
export default function CallInvites({socket,onAccept,onError}:{socket:Socket,onAccept:(room:any,mode:'voice'|'listen')=>void,onError:(s:string)=>void}){
 const [incoming,setIncoming]=useState<any>(null),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[remaining,setRemaining]=useState(45);const sound=useRef<AudioContext|null>(null);const callbacks=useRef({onAccept,onError});callbacks.current={onAccept,onError};
 useEffect(()=>{const unlock=()=>{if(!sound.current)sound.current=new AudioContext();void sound.current.resume().catch(()=>{});};window.addEventListener('pointerdown',unlock,{once:true});return()=>{window.removeEventListener('pointerdown',unlock);void sound.current?.close();sound.current=null;};},[]);
 useEffect(()=>{const receive=(r:any)=>{setIncoming(r);setRemaining(Math.max(0,Math.ceil((new Date(r.expires_at).getTime()-Date.now())/1000)));};const ended=(r:any)=>setIncoming((old:any)=>old?.id===r.id?null:old);const status=(r:any)=>{setResult(labels[r.status]||'Chamada atualizada');};const clear=()=>setIncoming(null);socket.on('ring-incoming',receive);socket.on('ring-ended',ended);socket.on('ring-result',status);socket.on('disconnect',clear);return()=>{socket.off('ring-incoming',receive);socket.off('ring-ended',ended);socket.off('ring-result',status);socket.off('disconnect',clear);};},[socket]);
 useEffect(()=>{if(!result)return;const t=setTimeout(()=>setResult(''),6500);return()=>clearTimeout(t);},[result]);
 useEffect(()=>{if(!incoming)return;const ring=()=>{const ctx=sound.current;if(ctx?.state==='running'){const gain=ctx.createGain();gain.gain.setValueAtTime(.06,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.65);gain.connect(ctx.destination);const oscillator=ctx.createOscillator();oscillator.frequency.value=540;oscillator.connect(gain);oscillator.start();oscillator.stop(ctx.currentTime+.65);oscillator.onended=()=>{gain.disconnect();oscillator.disconnect();};}};ring();const tone=setInterval(ring,2200);const time=setInterval(()=>{const left=Math.max(0,Math.ceil((new Date(incoming.expires_at).getTime()-Date.now())/1000));setRemaining(left);if(!left)setIncoming(null);},1000);return()=>{clearInterval(tone);clearInterval(time);};},[incoming]);
 async function respond(action:'accept'|'decline',mode:'voice'|'listen'='voice'){if(!incoming)return;setBusy(true);try{const r=await api('/rings/'+incoming.id+'/respond','POST',{action});setIncoming(null);if(action==='accept')callbacks.current.onAccept({...r.room,acceptedCall:true,joinMode:mode},mode);}catch(e:any){callbacks.current.onError(e.message);setIncoming(null);}finally{setBusy(false);}}
 return <>{incoming&&<div className="incoming-call" role="dialog" aria-modal="true" aria-label="Chamada recebida"><span className="ring-avatar">{incoming.caller.avatar_id?<img src={'/api/files/'+incoming.caller.avatar_id} alt=""/>:<Phone size={33}/>}</span><span className="eyebrow">CHAMADA RECEBIDA · {remaining}s</span><h2>{incoming.caller.name}</h2><p>está chamando em {incoming.room.name}</p><div className="ring-actions"><button className="danger-solid" disabled={busy} onClick={()=>void respond('decline')}><PhoneOff/>Recusar</button><button className="accept-call" disabled={busy} onClick={()=>void respond('accept')}><Phone/>Aceitar</button></div><button disabled={busy} onClick={()=>void respond('accept','listen')}><Headphones size={16}/>Aceitar só ouvindo</button><small>O microfone só é solicitado depois de aceitar.</small></div>}{result&&<div className="ring-result" role="status"><Phone size={15}/>{result}<button aria-label="Fechar resultado da chamada" onClick={()=>setResult('')}><X size={15}/></button></div>}</>;
}
export function CallHistory({onCall}:{onCall:(id:string)=>void}){const [rows,setRows]=useState<any[]>([]),[error,setError]=useState('');useEffect(()=>{void api('/calls/history').then(setRows).catch(e=>setError(e.message));},[]);return <div className="page-content"><div className="page-title"><div><span className="eyebrow">SUAS CONEXÕES</span><h1>Histórico de chamadas.</h1></div></div>{error&&<p className="error">{error}</p>}{rows.length?rows.map(r=><div className="history-row" key={r.id}><PhoneMissed size={20}/><div><strong>{r.caller_name} → {r.recipient_name}</strong><small>{labels[r.status]} · {new Date(r.created_at).toLocaleString('pt-BR')}</small></div><button onClick={()=>onCall(r.room_id)}><Phone size={16}/>Retornar</button></div>):<div className="empty"><Phone size={35}/><h3>As próximas conversas aparecem aqui.</h3><p>Chamadas recebidas, aceitas, recusadas e perdidas.</p></div>}</div>;}
