import {useEffect,useState,useRef,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {api} from './api';
type Layout={folders:{id:string,name:string,servers:string[]}[],order:string[]};
const empty:Layout={folders:[],order:[]};
function Editor({children,close}:{children:ReactNode,close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return createPortal(<dialog ref={ref} className="folder-editor" aria-label="Organizar comunidades" onCancel={close} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}}}>{children}</dialog>,document.body);}
export default function CommunityFolders({servers,active,select}:{servers:any[],active:string|null,select:(s:any)=>void}){
 const [layout,setLayout]=useState<Layout>(empty),[loaded,setLoaded]=useState(false),[editing,setEditing]=useState(false),[open,setOpen]=useState<string[]>([]),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;api('/community-layout').then(x=>{if(live){setLayout(x);setLoaded(true);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 async function save(value:Layout){if(busy)return;setBusy(true);setError('');try{setLayout(await api('/community-layout','PUT',value));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const ordered=[...servers].sort((a,b)=>{const ai=layout.order.indexOf(a.id),bi=layout.order.indexOf(b.id);return (ai<0?9999:ai)-(bi<0?9999:bi);});
 const icon=(s:any)=><button draggable={!busy&&loaded} onDragStart={e=>e.dataTransfer.setData('text/nexo-server',s.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=e.dataTransfer.getData('text/nexo-server');if(!servers.some(s=>s.id===from)||from===s.id)return;const order=ordered.map(s=>s.id).filter(id=>id!==from);order.splice(order.indexOf(s.id),0,from);void save({...layout,order});}} key={s.id} className={'server-icon '+(active===s.id?'selected':'')} title={s.name} onClick={()=>select(s)}>{s.icon_id?<img src={'/api/files/'+s.icon_id} alt=""/>:s.name.slice(0,2).toUpperCase()}</button>;
 function move(id:string,delta:number){const order=ordered.map(s=>s.id),i=order.indexOf(id),j=i+delta;if(j<0||j>=order.length)return;[order[i],order[j]]=[order[j],order[i]];void save({...layout,order});}
 return <><button title="Organizar comunidades" onClick={()=>setEditing(!editing)}>▦</button>{layout.folders.map(f=><div className="community-folder" key={f.id}><button className={f.servers.includes(active||'')?'folder-active':''} title={'Pasta '+f.name} aria-expanded={open.includes(f.id)} onClick={()=>setOpen(o=>o.includes(f.id)?o.filter(id=>id!==f.id):[...o,f.id])}>▣<small>{f.name}</small></button>{open.includes(f.id)&&ordered.filter(s=>f.servers.includes(s.id)).map(icon)}</div>)}{ordered.filter(s=>!layout.folders.some(f=>f.servers.includes(s.id))).map(icon)}{editing&&<Editor close={()=>setEditing(false)}><header><h3>Suas comunidades</h3><button onClick={()=>setEditing(false)} aria-label="Fechar organização">×</button></header><p>Arraste os ícones para ordenar ou use as setas abaixo. As pastas são pessoais e ficam salvas na sua conta.</p><form onSubmit={e=>{e.preventDefault();if(name.trim())void save({...layout,folders:[...layout.folders,{id:crypto.randomUUID(),name:name.trim(),servers:[]}]}).then(()=>setName(''));}}><label>Nome da pasta<input maxLength={30} required value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={busy||!loaded||layout.folders.length>=20}>Criar pasta</button></form>{layout.folders.map(f=><div className="folder-row" key={f.id}><span>{f.name}</span><button disabled={busy} onClick={()=>void save({...layout,folders:layout.folders.filter(x=>x.id!==f.id)})}>Desfazer pasta</button></div>)}{ordered.map((s,i)=><div className="folder-row" key={s.id}><strong>{s.name}</strong><select aria-label={'Pasta de '+s.name} disabled={busy||!loaded} value={layout.folders.find(f=>f.servers.includes(s.id))?.id||''} onChange={e=>void save({...layout,folders:layout.folders.map(f=>({...f,servers:[...f.servers.filter(id=>id!==s.id),...(f.id===e.target.value?[s.id]:[])]}))})}><option value="">Sem pasta</option>{layout.folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button disabled={busy||i===0||!loaded} aria-label={'Subir '+s.name} onClick={()=>move(s.id,-1)}>↑</button><button disabled={busy||i===ordered.length-1||!loaded} aria-label={'Descer '+s.name} onClick={()=>move(s.id,1)}>↓</button></div>)}{error&&<p role="alert">{error}</p>}</Editor>}</>;
}
