import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Download,X} from 'lucide-react';
let pending:any=null;
window.addEventListener('beforeinstallprompt',(event:any)=>{event.preventDefault();pending=event;window.dispatchEvent(new Event('nexo-install-ready'));});
const standalone=()=>matchMedia('(display-mode: standalone)').matches||!!(navigator as any).standalone;
export default function InstallApp(){const [installed,setInstalled]=useState(standalone),[open,setOpen]=useState(false),[available,setAvailable]=useState(!!pending),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const close=useRef<HTMLButtonElement>(null),trigger=useRef<HTMLButtonElement>(null);const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
 useEffect(()=>{const ready=()=>setAvailable(!!pending),done=()=>{pending=null;setInstalled(true);setOpen(false);},media=matchMedia('(display-mode: standalone)'),changed=()=>setInstalled(standalone());window.addEventListener('nexo-install-ready',ready);window.addEventListener('appinstalled',done);media.addEventListener('change',changed);return()=>{window.removeEventListener('nexo-install-ready',ready);window.removeEventListener('appinstalled',done);media.removeEventListener('change',changed);};},[]);
 useEffect(()=>{if(!open)return;close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[open]);
 async function install(){const event=pending;if(!event)return;pending=null;setAvailable(false);setBusy(true);try{await event.prompt();const result=await event.userChoice;setMessage(result.outcome==='accepted'?'Pedido aceito. Aguarde a confirmação do navegador.':'Instalação cancelada. Você pode continuar usando pelo navegador.');}catch{setMessage('Use o menu do navegador para instalar.');}finally{setBusy(false);}}
 if(installed)return null;
 return <><button ref={trigger} className="install-app-button" title="Instalar NexoChat" aria-label="Instalar NexoChat" onClick={()=>setOpen(true)}><Download size={18}/><span>Instalar app</span></button>{open&&createPortal(<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><section className="modal install-dialog" role="dialog" aria-modal="true" aria-label="Instalar NexoChat"><header><h2>NexoChat no seu aparelho</h2><button ref={close} aria-label="Fechar instalação" onClick={()=>{setOpen(false);trigger.current?.focus();}}><X/></button></header><img className="install-logo" src="/icon-192.png" alt="Ícone do NexoChat"/><p>Abra pelo ícone no celular ou no computador, em uma janela própria.</p>{available?<button className="primary" disabled={busy} onClick={()=>void install()}>Instalar neste aparelho</button>:ios?<ol><li>Abra este site no Safari.</li><li>Toque em Compartilhar.</li><li>Escolha Adicionar à Tela de Início e confirme em Adicionar.</li></ol>:/Android/.test(navigator.userAgent)?<ol><li>Abra este site no Chrome.</li><li>No menu ⋮, procure Instalar app ou Adicionar à tela inicial.</li><li>Confirme a instalação.</li></ol>:<p>No Chrome ou Edge, procure o ícone de instalação na barra de endereço ou a opção de instalar este site no menu do navegador. Se ela não aparecer, atualize a página e confira se está usando HTTPS.</p>}<p className="hint">Mensagens e chamadas precisam de internet. A instalação não garante chamadas com a tela bloqueada ou com o aplicativo fechado.</p>{message&&<p role="status">{message}</p>}</section></div>,document.body)}</>;
}
