import {useEffect,useState} from 'react';
import {api} from './api';
import {FeatureForm} from './CommunityHub';
export default function ServerStudio({server,me,onUpdated,onLeft,initial='identity'}:{server:string,me:string,onUpdated:()=>Promise<void>,onLeft?:()=>Promise<void>,initial?:string}){
 const [data,setData]=useState<any>(null),[draft,setDraft]=useState<any>(null),[tab,setTab]=useState(initial),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[leaving,setLeaving]=useState(false),[choice,setChoice]=useState('');
 async function load(){const d=await api('/servers/'+server+'/setup');setData(d);setDraft({name:d.server.name,bio:d.server.bio,icon_id:d.server.icon_id,banner_id:d.server.banner_id,welcome:d.server.welcome,rules:d.server.rules});setChoice(d.server.role_id||'');}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[server]);
 async function action(fn:()=>Promise<any>,note='Salvo!'){setBusy(true);setError('');try{await fn();await load();await onUpdated();setNotice(note);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function upload(file:File|undefined,key:string){if(!file)return;setBusy(true);setError('');try{const d=new FormData();d.append('file',file);const a=await api('/upload','POST',d);setDraft((old:any)=>({...old,[key]:a.id}));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 if(!data)return <p>{error||'Carregando comunidade…'}</p>;const owner=data.server.owner_id===me,selected=data.roles.find((r:any)=>r.id===data.server.role_id),managed=data.server.role_id&&!selected?.self_assignable;const accepted=!data.server.rules||data.server.accepted_rules>=data.server.rules_version||owner;
 return <div className="server-studio feature-stack">{owner&&<div className="tabs">{[['identity','Foto, banner e bio'],['welcome','Boas-vindas e cargos'],['roles','Cargos por conquistas'],['ownership','Transferir propriedade']].map(([id,name])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{name}</button>)}</div>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {owner&&tab==='identity'&&<form className="feature-stack server-identity" onSubmit={e=>{e.preventDefault();void action(()=>api('/servers/'+server+'/settings','PATCH',draft),'Comunidade atualizada!');}}><div className="community-cover">{draft.banner_id&&<img src={'/api/files/'+draft.banner_id} alt="Banner da comunidade"/>}<div>{draft.icon_id?<img src={'/api/files/'+draft.icon_id} alt="Foto da comunidade"/>:<b>{draft.name.slice(0,2)}</b>}<h2>{draft.name}</h2></div></div><label>Nome da comunidade<input value={draft.name} required maxLength={60} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Bio da comunidade<textarea maxLength={500} value={draft.bio} onChange={e=>setDraft({...draft,bio:e.target.value})}/></label>{[['icon_id','Foto'],['banner_id','Banner']].map(([key,name])=><div key={key}><label>{name} da comunidade (até 2 MB)<input type="file" disabled={busy} accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>void upload(e.target.files?.[0],key)}/></label>{draft[key]&&<button type="button" onClick={()=>setDraft({...draft,[key]:null})}>Remover {name.toLowerCase()}</button>}</div>)}<label>Mensagem de boas-vindas<textarea maxLength={1000} value={draft.welcome} onChange={e=>setDraft({...draft,welcome:e.target.value})}/></label><label>Regras da comunidade<textarea rows={6} maxLength={4000} value={draft.rules} onChange={e=>setDraft({...draft,rules:e.target.value})}/></label><small>Ao mudar as regras, os membros precisarão aceitar a nova versão antes de enviar mensagens ou entrar em chamadas.</small><button className="primary" disabled={busy}>Salvar comunidade</button></form>}
 {(!owner||tab==='welcome')&&<><h2>Bem-vindo(a) a {data.server.name}</h2><p className="preserve-lines">{data.server.welcome||'Este é o ponto de encontro da sua turma.'}</p>{data.server.rules&&<section className="feature-card"><h3>Regras · versão {data.server.rules_version}</h3><p className="preserve-lines">{data.server.rules}</p><button disabled={busy||accepted} onClick={()=>void action(()=>api('/servers/'+server+'/rules/accept','POST',{version:data.server.rules_version}),'Regras aceitas!')}>{accepted?'Regras aceitas':'Li e aceito as regras'}</button></section>}<h3>Seu cargo na comunidade</h3><small>Um cargo ativo por pessoa. Conquistas são resgatadas em Insígnias e conquistas; mensagens repetidas não liberam cargos.</small>{managed?<p>Seu cargo foi atribuído pela administração. Peça ao dono para alterá-lo.</p>:<><label>Escolher cargo<select value={choice} disabled={!accepted||busy} onChange={e=>setChoice(e.target.value)}><option value="">Membro</option>{data.roles.filter((r:any)=>r.self_assignable).map((r:any)=><option key={r.id} value={r.id} disabled={!r.eligible}>{r.name}{r.required_badge?' · exige '+(data.badges.find((b:any)=>b.id===r.required_badge)?.name||r.required_badge):''}{!r.eligible?' (bloqueado)':''}</option>)}</select></label><button disabled={busy||!accepted} onClick={()=>void action(()=>api('/servers/'+server+'/choose-role','POST',{role_id:choice||null}),'Cargo atualizado!')}>Usar cargo escolhido</button></>}{data.offer?.target_id===me&&<section className="feature-card"><h3>Você foi convidado a ser o dono</h3><p>Ao aceitar, você assume a administração e o antigo dono vira membro.</p><button disabled={busy} className="primary" onClick={()=>void action(()=>api('/servers/'+server+'/transfer/respond','POST',{accept:true}),'Você é o novo dono da comunidade.')}>Aceitar propriedade</button><button disabled={busy} onClick={()=>void action(()=>api('/servers/'+server+'/transfer/respond','POST',{accept:false}),'Convite recusado.')}>Recusar transferência</button></section>}{!owner&&onLeft&&<section className="feature-card"><button className="danger" onClick={()=>setLeaving(!leaving)}>Sair da comunidade</button>{leaving&&<><p>Você perderá acesso aos canais. Suas mensagens permanecem; para voltar será necessário um convite.</p><button disabled={busy} className="danger-solid" onClick={async()=>{setBusy(true);try{await api('/servers/'+server+'/leave','POST');await onLeft();}catch(e:any){setError(e.message);setBusy(false);}}}>Confirmar saída</button></>}</section>}</>}
 {owner&&tab==='roles'&&<><FeatureForm label="Criar cargo para membros" onSubmit={async d=>{await api('/servers/'+server+'/roles','POST',{name:d.get('name'),permissions:['send','invite']});await load();await onUpdated();}}><label>Nome do novo cargo<input name="name" required maxLength={60}/></label></FeatureForm><p>Escolha cargos comuns para a entrada ou vincule a uma conquista. Cargos administrativos nunca podem ser escolhidos pelos membros.</p>{data.roles.map((r:any)=>{const safe=r.permissions.every((p:string)=>['send','invite'].includes(p));return <details className="feature-card" key={r.id}><summary>{r.name}</summary>{safe?<FeatureForm label={'Salvar liberação de '+r.name} onSubmit={async d=>{await api('/servers/'+server+'/roles/'+r.id+'/unlock','PATCH',{self_assignable:d.get('enabled')==='on',required_badge:d.get('badge')||null});await load();await onUpdated();setNotice('Cargo configurado.');}}><label className="check"><input name="enabled" type="checkbox" defaultChecked={r.self_assignable}/>Permitir escolha pelo membro</label><label>Conquista necessária<select name="badge" defaultValue={r.required_badge||''}><option value="">Nenhuma · disponível na entrada</option>{data.badges.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></FeatureForm>:<p>Este cargo tem poderes de administração e só pode ser atribuído pelo dono.</p>}</details>;})}</>}
 {owner&&tab==='ownership'&&<><p>O novo dono precisa ser membro e aceitar o convite em até 7 dias. Até lá, você continua como dono.</p>{data.offer&&<p>Convite pendente para {data.offer.target_name}, até {new Date(data.offer.expires_at).toLocaleString('pt-BR')} <button onClick={()=>void action(()=>api('/servers/'+server+'/transfer','DELETE'),'Transferência cancelada.')}>Cancelar transferência</button></p>}<FeatureForm label="Convidar novo dono" onSubmit={async d=>{await api('/servers/'+server+'/transfer','POST',{target_id:d.get('target'),name:d.get('name')});await load();setNotice('Convite de transferência enviado.');}}><label>Novo dono<select name="target" required defaultValue=""><option value="" disabled>Escolha um membro</option>{data.members.filter((m:any)=>m.user_id!==me).map((m:any)=><option key={m.user_id} value={m.user_id}>{m.display_name} (@{m.username})</option>)}</select></label><label>Confirme o nome da comunidade<input name="name" required placeholder={data.server.name} maxLength={60}/></label></FeatureForm><p>Para sair sendo dono, conclua a transferência primeiro.</p></>}
 </div>;
}
