import {useEffect,useState} from 'react';
declare const __NEXO_BUILD__:{version:string,id:string,builtAt:string};
export const build=__NEXO_BUILD__;
export function Updates({inCall=false,compact=false}:{inCall?:boolean,compact?:boolean}){
 const [next,setNext]=useState<typeof build|null>(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
 async function check(manual=false){if(manual)setBusy(true);try{const res=await fetch('/version.json?t='+Date.now(),{cache:'no-store'});if(!res.ok)throw Error();const value=await res.json();if(typeof value.id!=='string'||typeof value.version!=='string')throw Error();setNext(value.id!==build.id?value:null);setNote(value.id!==build.id?'Nova versão disponível.':manual?'Você está na versão publicada mais recente.':'');}catch{if(manual)setNote('Não foi possível verificar agora. Tente novamente quando estiver conectado.');}finally{if(manual)setBusy(false);}}
 useEffect(()=>{void check();const timer=setInterval(()=>{if(document.visibilityState==='visible')void check();},120000);const focus=()=>void check();window.addEventListener('online',focus);window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('online',focus);window.removeEventListener('focus',focus);};},[]);
 async function update(){if(inCall||document.querySelector('.call')){setNote('Encerre a chamada antes de atualizar.');return;}if(!window.confirm('Atualizar o NexoChat agora? Mensagens ainda não enviadas serão perdidas.'))return;setBusy(true);try{if('serviceWorker' in navigator){const r=await navigator.serviceWorker.getRegistration();await r?.update();}location.reload();}catch{location.reload();}}
 if(compact&&!next)return null;
 return <section className={compact?'update-banner':'feature-stack'} aria-live="polite">{!compact&&<><h3>NexoChat {build.version}</h3><small>Compilação {build.id.slice(0,8)} · {new Date(build.builtAt).toLocaleString('pt-BR')}</small><button disabled={busy} onClick={()=>void check(true)}>Verificar atualizações</button></>}{next&&<><strong>Nova versão disponível · {next.version}</strong><button disabled={busy||inCall} onClick={()=>void update()}>Atualizar aplicativo</button>{inCall&&<small>Encerre a chamada para atualizar com segurança.</small>}</>}{note&&<p role="status">{note}</p>}</section>;
}
export function News({inCall=false}:{inCall?:boolean}){return <div className="feature-stack"><Updates inCall={inCall}/><h3>Novidades · 0.8.0</h3><ul><li>Pastas e ordem das comunidades salvas na sua conta.</li><li>Grave um teste curto e ouça sua voz antes de entrar na chamada.</li><li>Busca por imagens, áudios, vídeos e documentos.</li><li>Atividades rápidas no perfil: jogando, estudando ou disponível para call.</li><li>Acompanhe suas denúncias e a resposta dos moderadores.</li><li>Aviso quando uma nova versão estiver publicada.</li></ul><h3>Também disponível</h3><p>PC + celular na mesma chamada, volume por pessoa, qualidade da conexão, emojis e figurinhas da comunidade e acessibilidade nas configurações.</p><p>Chamadas precisam de internet. Esta versão ainda não tem E2EE nem notificações push com o app fechado.</p></div>;}

