import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {BADGES} from '@nexo/shared/badges';
import {guardSend} from './community-features.js';
import type {DB,QueryDb} from './db.js';
const id=z.string().uuid();
const fail=(status:number,message:string):never=>{throw Object.assign(new Error(message),{status});};
const safeRole=(r:any)=>r&&r.self_assignable&&Array.isArray(r.permissions)&&r.permissions.every((p:string)=>['send','invite'].includes(p));
export function communityPlus(o:any){const {app,route,access,serverAccess,blocked,refresh,evictRoom,members,notify}=o;const db:DB=o.db;
 const first=async(sql:string,args:any[]=[]) => (await db.query(sql,args))[0];
 async function owner(user:string,sid:string){const s=await serverAccess(user,sid);if(s.owner_id!==user)fail(403,'Somente o dono pode fazer isso');return s;}
 app.get('/api/servers/:id/setup',route(async(req:any,res:any)=>{const s=await serverAccess(req.user.id,req.params.id);const roles=await db.query('SELECT * FROM roles WHERE server_id=$1 ORDER BY name',[s.id]);const earned=await db.query('SELECT badge_id FROM user_badges WHERE user_id=$1',[req.user.id]);const offers=await first('SELECT o.*,u.display_name AS target_name FROM ownership_offers o JOIN users u ON u.id=o.target_id WHERE o.server_id=$1 AND o.expires_at>now()',[s.id]);const roster=await db.query('SELECT m.user_id,m.role_id,u.username,u.display_name FROM server_members m JOIN users u ON u.id=m.user_id WHERE m.server_id=$1 AND NOT m.banned ORDER BY u.display_name',[s.id]);res.json({server:s,roles:roles.filter(r=>s.owner_id===req.user.id||safeRole(r)).map(r=>({...r,eligible:!r.required_badge||earned.some(b=>b.badge_id===r.required_badge)})),offer:s.owner_id===req.user.id||offers?.target_id===req.user.id?offers:null,members:roster,badges:BADGES});}));
 app.patch('/api/servers/:id/settings',route(async(req:any,res:any)=>{const s=await owner(req.user.id,req.params.id);const x=z.object({name:z.string().trim().min(1).max(60),bio:z.string().trim().max(500),icon_id:id.nullable(),banner_id:id.nullable(),welcome:z.string().max(1000),rules:z.string().max(4000)}).strict().parse(req.body);for(const a of [x.icon_id,x.banner_id])if(a&&a!==s.icon_id&&a!==s.banner_id&&!await first("SELECT 1 FROM attachments WHERE id=$1 AND owner_id=$2 AND room_id IS NULL AND mime LIKE 'image/%'",[a,req.user.id]))fail(400,'Use uma imagem própria de até 2 MB');const updated=await db.query('UPDATE servers SET name=$2,bio=$3,icon_id=$4,banner_id=$5,welcome=$6,rules_version=rules_version+CASE WHEN rules<>$7 THEN 1 ELSE 0 END,rules=$7 WHERE id=$1 AND owner_id=$8 RETURNING id',[s.id,x.name,x.bio,x.icon_id,x.banner_id,x.welcome,x.rules,req.user.id]);if(!updated.length)fail(403,'A propriedade da comunidade mudou');refresh();res.json({ok:true});}));
 app.post('/api/servers/:id/transfer',route(async(req:any,res:any)=>{const x=z.object({target_id:id,name:z.string().max(60)}).strict().parse(req.body);await db.transaction(async tx=>{const [s]=await tx.query('SELECT * FROM servers WHERE id=$1 FOR UPDATE',[id.parse(req.params.id)]);if(!s||s.owner_id!==req.user.id)fail(403,'Somente o dono pode transferir');if(x.name!==s.name||x.target_id===req.user.id)fail(400,'Confirme o nome e escolha outro membro');const [m]=await tx.query('SELECT * FROM server_members WHERE server_id=$1 AND user_id=$2 AND NOT banned',[s.id,x.target_id]);if(!m)fail(400,'Escolha um membro da comunidade');await tx.query("INSERT INTO ownership_offers(server_id,target_id,expires_at) VALUES($1,$2,now()+interval '7 days') ON CONFLICT(server_id) DO UPDATE SET target_id=$2,expires_at=now()+interval '7 days'",[s.id,x.target_id]);await tx.query('INSERT INTO notifications(id,user_id,actor_id,body) VALUES($1,$2,$3,$4)',[randomUUID(),x.target_id,req.user.id,'Você foi convidado a assumir '+s.name+'. Abra Boas-vindas e cargos nessa comunidade para aceitar.']);});refresh();res.json({ok:true});}));
 app.post('/api/servers/:id/transfer/respond',route(async(req:any,res:any)=>{const accept=z.boolean().parse(req.body.accept);let previousOwner:string|null=null;await db.transaction(async tx=>{const sid=id.parse(req.params.id),[s]=await tx.query('SELECT * FROM servers WHERE id=$1 FOR UPDATE',[sid]);const [offer]=await tx.query('SELECT * FROM ownership_offers WHERE server_id=$1 AND expires_at>now()',[sid]);if(!s||!offer||offer.target_id!==req.user.id)fail(403,'Transferência indisponível');const [m]=await tx.query('SELECT * FROM server_members WHERE server_id=$1 AND user_id=$2 AND NOT banned',[sid,req.user.id]);if(!m)fail(403,'Você precisa ser membro');if(accept){previousOwner=s.owner_id;await tx.query('UPDATE servers SET owner_id=$2 WHERE id=$1',[sid,req.user.id]);await tx.query('UPDATE rooms SET owner_id=$2 WHERE server_id=$1',[sid,req.user.id]);await tx.query('INSERT INTO audit(id,server_id,actor_id,action) VALUES($1,$2,$3,$4)',[randomUUID(),sid,req.user.id,'ownership_transfer: '+s.owner_id+' → '+req.user.id]);}await tx.query('DELETE FROM ownership_offers WHERE server_id=$1',[sid]);});if(previousOwner)for(const r of await db.query('SELECT id FROM rooms WHERE server_id=$1',[req.params.id]))await evictRoom(r.id,previousOwner);refresh();res.json({ok:true});}));
 app.delete('/api/servers/:id/transfer',route(async(req:any,res:any)=>{await owner(req.user.id,req.params.id);await db.query('DELETE FROM ownership_offers WHERE server_id=$1',[req.params.id]);refresh();res.json({ok:true});}));
 app.post('/api/servers/:id/leave',route(async(req:any,res:any)=>{const sid=id.parse(req.params.id);await db.transaction(async tx=>{const [s]=await tx.query('SELECT * FROM servers WHERE id=$1 FOR UPDATE',[sid]);if(!s)fail(404,'Comunidade não encontrada');if(s.owner_id===req.user.id)fail(409,'Transfira a propriedade antes de sair');await tx.query('DELETE FROM server_members WHERE server_id=$1 AND user_id=$2',[sid,req.user.id]);await tx.query('DELETE FROM ownership_offers WHERE server_id=$1 AND target_id=$2',[sid,req.user.id]);await tx.query('DELETE FROM room_members WHERE user_id=$1 AND room_id IN (SELECT id FROM rooms WHERE server_id=$2)',[req.user.id,sid]);await tx.query('DELETE FROM event_reminders WHERE user_id=$1 AND event_id IN (SELECT id FROM community_events WHERE server_id=$2)',[req.user.id,sid]);});for(const r of await db.query('SELECT id FROM rooms WHERE server_id=$1',[sid]))await evictRoom(r.id,req.user.id);refresh();res.json({ok:true});}));
 app.post('/api/servers/:id/rules/accept',route(async(req:any,res:any)=>{await serverAccess(req.user.id,req.params.id);const version=z.number().int().nonnegative().parse(req.body.version);const rows=await db.query('UPDATE server_members m SET accepted_rules=$3 FROM servers s WHERE s.id=m.server_id AND m.server_id=$1 AND m.user_id=$2 AND NOT m.banned AND s.rules_version=$3 RETURNING m.user_id',[req.params.id,req.user.id,version]);if(!rows.length)fail(409,'As regras mudaram. Atualize a página.');refresh();res.json({ok:true});}));
 app.patch('/api/servers/:id/roles/:role/unlock',route(async(req:any,res:any)=>{await owner(req.user.id,req.params.id);const x=z.object({self_assignable:z.boolean(),required_badge:z.string().max(30).nullable()}).strict().parse(req.body);if(x.required_badge&&!BADGES.some(b=>b.id===x.required_badge))fail(400,'Conquista inválida');const r=await first('SELECT * FROM roles WHERE id=$1 AND server_id=$2',[id.parse(req.params.role),req.params.id]);if(!r)fail(404,'Cargo não encontrado');if(x.self_assignable&&r.permissions.some((p:string)=>!['send','invite'].includes(p)))fail(400,'Cargos de entrada/conquista não podem ter poderes de moderação');await db.query('UPDATE roles SET self_assignable=$2,required_badge=$3 WHERE id=$1',[r.id,x.self_assignable,x.required_badge]);refresh();res.json({ok:true});}));
 app.post('/api/servers/:id/choose-role',route(async(req:any,res:any)=>{await serverAccess(req.user.id,req.params.id,'send');const role=id.nullable().parse(req.body.role_id);await db.transaction(async tx=>{const [m]=await tx.query('SELECT * FROM server_members WHERE server_id=$1 AND user_id=$2 AND NOT banned FOR UPDATE',[req.params.id,req.user.id]);if(!m)fail(403,'Sem acesso');if(m.role_id){const [current]=await tx.query('SELECT * FROM roles WHERE id=$1',[m.role_id]);if(!safeRole(current))fail(403,'Seu cargo é gerenciado pelo dono; peça a alteração a ele.');}if(role){const [r]=await tx.query('SELECT * FROM roles WHERE id=$1 AND server_id=$2',[role,req.params.id]);if(!safeRole(r))fail(403,'Cargo indisponível para escolha');if(r.required_badge&&!(await tx.query('SELECT 1 FROM user_badges WHERE user_id=$1 AND badge_id=$2',[req.user.id,r.required_badge])).length)fail(403,'Resgate a conquista exigida antes de escolher este cargo');}await tx.query('UPDATE server_members SET role_id=$3 WHERE server_id=$1 AND user_id=$2',[req.params.id,req.user.id,role]);});for(const r of await db.query('SELECT id FROM rooms WHERE server_id=$1',[req.params.id]))await evictRoom(r.id,req.user.id);refresh();res.json({ok:true});}));
 app.patch('/api/rooms/:id/notifications',route(async(req:any,res:any)=>{const r=await access(req.user.id,req.params.id),mode=z.enum(['all','mentions','muted']).parse(req.body.mode);await db.query('INSERT INTO room_members(room_id,user_id,notification_mode,muted) VALUES($1,$2,$3,$4) ON CONFLICT(room_id,user_id) DO UPDATE SET notification_mode=$3,muted=$4',[r.id,req.user.id,mode,mode==='muted']);refresh();res.json({ok:true});}));
 app.get('/api/call-preferences',route(async(req:any,res:any)=>res.json(await db.query('SELECT peer_id,volume FROM call_preferences WHERE user_id=$1',[req.user.id]))));
 app.put('/api/call-preferences/:id',route(async(req:any,res:any)=>{const peer=id.parse(req.params.id),volume=z.number().int().min(0).max(100).parse(req.body.volume);await db.query('INSERT INTO call_preferences(user_id,peer_id,volume) VALUES($1,$2,$3) ON CONFLICT(user_id,peer_id) DO UPDATE SET volume=$3',[req.user.id,peer,volume]);res.json({ok:true});}));
 const tags=z.array(z.string().trim().min(1).max(24)).max(12).refine(a=>new Set(a.map(s=>s.toLowerCase())).size===a.length,'Etiquetas repetidas');
 app.patch('/api/rooms/:id/forum-tags',route(async(req:any,res:any)=>{const r=await access(req.user.id,req.params.id,'manage_channels');if(r.kind!=='forum')fail(400,'Canal não é fórum');await db.query('UPDATE rooms SET forum_tags=$2 WHERE id=$1',[r.id,JSON.stringify(tags.parse(req.body.tags))]);refresh();res.json({ok:true});}));
 app.get('/api/rooms/:id/forum',route(async(req:any,res:any)=>{const r=await access(req.user.id,req.params.id);if(r.kind!=='forum')fail(400,'Canal não é fórum');const tag=z.string().max(24).optional().parse(req.query.tag),q=z.string().max(100).default('').parse(req.query.q),offset=z.coerce.number().int().min(0).max(100000).default(0).parse(req.query.offset);const topics=await db.query(`SELECT m.*,u.display_name,t.title,t.closed,f.tags,(SELECT count(*)::int FROM messages replies WHERE replies.thread_id=m.id AND NOT replies.deleted AND NOT EXISTS(SELECT 1 FROM relations b WHERE b.state='blocked' AND (b.sender=$2 AND b.recipient=replies.user_id OR b.recipient=$2 AND b.sender=replies.user_id))) AS replies FROM forum_topics f JOIN threads t ON t.id=f.message_id JOIN messages m ON m.id=t.id JOIN users u ON u.id=m.user_id WHERE m.room_id=$1 AND NOT m.deleted AND ($3::text IS NULL OR f.tags ? $3) AND (position(lower($4) in lower(t.title||' '||m.body))>0) AND NOT EXISTS(SELECT 1 FROM relations b WHERE b.state='blocked' AND (b.sender=$2 AND b.recipient=m.user_id OR b.recipient=$2 AND b.sender=m.user_id)) ORDER BY m.created_at DESC,m.id DESC LIMIT 31 OFFSET $5`,[r.id,req.user.id,tag||null,q,offset]);res.json({topics:topics.slice(0,30),next:topics.length>30?offset+30:null,tags:r.forum_tags});}));
 app.post('/api/rooms/:id/forum',route(async(req:any,res:any)=>{const r=await access(req.user.id,req.params.id,'send');if(r.kind!=='forum')fail(400,'Canal não é fórum');const x=z.object({title:z.string().trim().min(1).max(80),body:z.string().trim().min(1).max(4000),tags:tags.refine(a=>a.length<=3,'Até 3 etiquetas por assunto')}).strict().parse(req.body);if(x.tags.some(t=>!r.forum_tags.includes(t)))fail(400,'Etiqueta indisponível');const mid=randomUUID();const s=await serverAccess(req.user.id,r.server_id);await db.transaction(async tx=>{await guardSend(tx,req.user.id,r,x.body,s.owner_id===req.user.id||s.permissions?.includes('manage_messages'));await tx.query('INSERT INTO messages(id,room_id,user_id,body) VALUES($1,$2,$3,$4)',[mid,r.id,req.user.id,x.body]);await tx.query('INSERT INTO threads(id,title) VALUES($1,$2)',[mid,x.title]);await tx.query('INSERT INTO forum_topics(message_id,tags) VALUES($1,$2)',[mid,JSON.stringify(x.tags)]);});for(const m of await members(r)){const u=await first('SELECT username FROM users WHERE id=$1',[m.user_id]);await notify(m.user_id,req.user.id,'Novo assunto: '+x.title,r.id,new RegExp('(^|\\s)@'+u.username+'(?=\\s|$|[.,!?])').test(x.body));}refresh();res.json({id:mid});}));
}
