import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import type {DB} from './db.js';
const fail=(status:number,message:string):never=>{throw Object.assign(new Error(message),{status});};
export function eventExtras({app,route,db,serverAccess,refresh}:{app:any,route:any,db:DB,serverAccess:any,refresh:()=>void}){
 async function event(user:string,eid:string,write=false){const [e]=await db.query('SELECT * FROM community_events WHERE id=$1',[z.string().uuid().parse(eid)]);if(!e)fail(404,'Evento não encontrado');const s=await serverAccess(user,e.server_id,write?'send':undefined);return {e,s};}
 app.get('/api/events/:id/extras',route(async(req:any,res:any)=>{const {e,s}=await event(req.user.id,req.params.id);const [poll]=await db.query('SELECT * FROM event_polls WHERE event_id=$1',[e.id]);const [reminder]=await db.query('SELECT minutes FROM event_reminders WHERE event_id=$1 AND user_id=$2',[e.id,req.user.id]);if(poll){poll.votes=await db.query('SELECT choice,count(*)::int AS total FROM event_poll_votes WHERE event_id=$1 GROUP BY choice',[e.id]);poll.choice=(await db.query('SELECT choice FROM event_poll_votes WHERE event_id=$1 AND user_id=$2',[e.id,req.user.id]))[0]?.choice??null;}res.json({poll:poll||null,reminder:reminder?.minutes??null,canManage:e.creator_id===req.user.id||s.owner_id===req.user.id||s.permissions?.includes('manage_channels'),ended:e.cancelled||new Date(e.starts_at).getTime()<=Date.now()});}));
 app.post('/api/events/:id/poll',route(async(req:any,res:any)=>{const {e,s}=await event(req.user.id,req.params.id,true);if(e.creator_id!==req.user.id&&s.owner_id!==req.user.id&&!s.permissions?.includes('manage_channels'))fail(403,'Somente organizador ou gerente');const x=z.object({question:z.string().trim().min(1).max(120),options:z.array(z.string().trim().min(1).max(80)).min(2).max(8).refine(a=>new Set(a.map(v=>v.toLowerCase())).size===a.length)}).strict().parse(req.body);if(e.cancelled||new Date(e.starts_at).getTime()<=Date.now())fail(409,'Evento encerrado');await db.query('INSERT INTO event_polls(event_id,question,options) VALUES($1,$2,$3)',[e.id,x.question,JSON.stringify(x.options)]);refresh();res.json({ok:true});}));
 app.post('/api/events/:id/poll/vote',route(async(req:any,res:any)=>{const {e}=await event(req.user.id,req.params.id,true);const choice=z.number().int().min(0).max(7).nullable().parse(req.body.choice);await db.transaction(async tx=>{const [current]=await tx.query('SELECT * FROM community_events WHERE id=$1 FOR UPDATE',[e.id]);const [p]=await tx.query('SELECT * FROM event_polls WHERE event_id=$1 FOR UPDATE',[e.id]);if(!p||p.closed||current.cancelled||new Date(current.starts_at).getTime()<=Date.now())fail(409,'Enquete encerrada');if(choice!==null&&choice>=p.options.length)fail(400,'Opção inválida');if(choice===null)await tx.query('DELETE FROM event_poll_votes WHERE event_id=$1 AND user_id=$2',[e.id,req.user.id]);else await tx.query('INSERT INTO event_poll_votes(event_id,user_id,choice) VALUES($1,$2,$3) ON CONFLICT(event_id,user_id) DO UPDATE SET choice=$3',[e.id,req.user.id,choice]);});refresh();res.json({ok:true});}));
 app.post('/api/events/:id/poll/close',route(async(req:any,res:any)=>{const {e,s}=await event(req.user.id,req.params.id,true);if(e.creator_id!==req.user.id&&s.owner_id!==req.user.id&&!s.permissions?.includes('manage_channels'))fail(403,'Somente organizador ou gerente');await db.query('UPDATE event_polls SET closed=true WHERE event_id=$1',[e.id]);refresh();res.json({ok:true});}));
 app.put('/api/events/:id/reminder',route(async(req:any,res:any)=>{const {e}=await event(req.user.id,req.params.id);const minutes=z.union([z.literal(0),z.literal(5),z.literal(15),z.literal(60),z.null()]).parse(req.body.minutes);if(minutes===null)await db.query('DELETE FROM event_reminders WHERE event_id=$1 AND user_id=$2',[e.id,req.user.id]);else{if(e.cancelled||new Date(e.starts_at).getTime()<=Date.now())fail(409,'Evento encerrado');await db.query('INSERT INTO event_reminders(event_id,user_id,minutes) VALUES($1,$2,$3) ON CONFLICT(event_id,user_id) DO UPDATE SET minutes=$3',[e.id,req.user.id,minutes]);}res.json({ok:true});}));
 let running:Promise<void>|null=null;
 async function deliver(){const due=await db.query("SELECT r.event_id,r.user_id FROM event_reminders r JOIN community_events e ON e.id=r.event_id JOIN server_members m ON m.server_id=e.server_id AND m.user_id=r.user_id WHERE NOT m.banned AND NOT e.cancelled AND e.starts_at>now()-interval '1 minute' AND e.starts_at<=now()+r.minutes*interval '1 minute' AND r.notified_start IS DISTINCT FROM e.starts_at LIMIT 100");let changed=false;for(const r of due){await db.transaction(async tx=>{const [row]=await tx.query("SELECT r.*,e.title,e.starts_at,e.cancelled,e.server_id FROM event_reminders r JOIN community_events e ON e.id=r.event_id WHERE r.event_id=$1 AND r.user_id=$2 FOR UPDATE OF r,e",[r.event_id,r.user_id]);if(!row||row.cancelled||row.notified_start&&new Date(row.notified_start).getTime()===new Date(row.starts_at).getTime())return;const [member]=await tx.query('SELECT 1 FROM server_members WHERE server_id=$1 AND user_id=$2 AND NOT banned',[row.server_id,r.user_id]);if(!member||new Date(row.starts_at).getTime()>Date.now()+row.minutes*60000||new Date(row.starts_at).getTime()<Date.now()-60000)return;await tx.query('INSERT INTO notifications(id,user_id,body) VALUES($1,$2,$3)',[randomUUID(),r.user_id,'Lembrete: '+row.title+' · '+new Date(row.starts_at).toISOString()]);await tx.query('UPDATE event_reminders SET notified_start=$3 WHERE event_id=$1 AND user_id=$2',[r.event_id,r.user_id,row.starts_at]);changed=true;});}if(changed)refresh();}
 const tick=()=>running??(running=deliver().finally(()=>{running=null;}));const timer=setInterval(()=>void tick().catch(console.error),15000);timer.unref();return {tick,close:async()=>{clearInterval(timer);await running;}};
}
