import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {PGlite} from '@electric-sql/pglite';
import {scryptSync,createDecipheriv,createCipheriv,randomBytes} from 'node:crypto';
import {gunzipSync,gzipSync} from 'node:zlib';
test('0.7: comunidade, propriedade, fórum, notificações, presentes, conquistas, chamadas, eventos e backup',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'nexo-seven-'));process.env.DATA_DIR=dir;process.env.DATABASE_URL='';process.env.APP_ORIGIN='http://localhost:5173';const {openDb}=await import('../src/db.js'),{migrate}=await import('../src/migrate.js'),{createApp}=await import('../src/app.js'),{createBackup,restoreBackup}=await import('../src/backup.js');const db=await openDb();await migrate(db);const svc=createApp(db);await new Promise<void>(r=>svc.http.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+(svc.http.address() as any).port,cookies:Record<string,string>={};
 async function req(w:string,p:string,method='GET',body?:any,status:number|number[]=200){const r=await fetch(base+'/api'+p,{method,headers:{Origin:process.env.APP_ORIGIN!,Cookie:cookies[w]||'',...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const c=r.headers.get('set-cookie');if(c)cookies[w]=c.split(';')[0];const d=await r.json();assert.ok((Array.isArray(status)?status:[status]).includes(r.status),w+' '+p+' status '+r.status+': '+JSON.stringify(d));return d;}
 try{
  for(const username of ['alice','bobby','carol'])await req(username,'/auth/register','POST',{username,password:'Strong-test-password-123'});const alice=(await req('alice','/state')).me,bob=(await req('bobby','/state')).me,carol=(await req('carol','/state')).me;
  await req('alice','/friends','POST',{username:'bobby'});await req('bobby','/friends/'+alice.id+'/accept','POST');const server=await req('alice','/servers','POST',{name:'Turma'});const sid=server.id,invite=await req('alice','/servers/'+sid+'/invites','POST');
  const form=new FormData();form.append('file',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z4Z8AAAAASUVORK5CYII=','base64')],{type:'image/png'}),'icon.png');const icon=await req('alice','/upload','POST',form);
  const identity={name:'Turma nova',bio:'Nossa comunidade',icon_id:icon.id,banner_id:icon.id,welcome:'Olá, seja bem-vindo!',rules:'Respeite a turma.'};await req('alice','/servers/'+sid+'/settings','PATCH',identity);await req('bobby','/invites/'+invite.code+'/join','POST');await req('carol','/servers/'+sid+'/setup','GET',undefined,403);await req('bobby','/servers/'+sid+'/settings','PATCH',identity,403);
  assert.ok((await req('bobby','/state')).notifications.some((n:any)=>n.body.includes('Olá, seja bem-vindo!')));assert.equal((await fetch(base+'/api/files/'+icon.id,{headers:{Cookie:cookies.bobby}})).status,200);assert.equal((await fetch(base+'/api/files/'+icon.id,{headers:{Cookie:cookies.carol}})).status,403);
  const room=(await req('alice','/state')).rooms.find((r:any)=>r.server_id===sid&&r.kind==='text');await req('bobby','/rooms/'+room.id+'/messages','POST',{body:'Ainda sem aceitar'},403);await req('bobby','/servers/'+sid+'/rules/accept','POST',{version:0},409);await req('bobby','/servers/'+sid+'/rules/accept','POST',{version:1});await req('bobby','/rooms/'+room.id+'/messages','POST',{body:'Regras aceitas'});
  await req('alice','/servers/'+sid+'/roles','POST',{name:'Explorador',permissions:['send','invite']});let setup=await req('alice','/servers/'+sid+'/setup');const role=setup.roles.find((r:any)=>r.name==='Explorador');await req('alice','/servers/'+sid+'/roles/'+role.id+'/unlock','PATCH',{self_assignable:true,required_badge:'regular'});await req('bobby','/servers/'+sid+'/choose-role','POST',{role_id:role.id},403);
  await req('alice','/servers/'+sid+'/roles/'+role.id+'/unlock','PATCH',{self_assignable:true,required_badge:null});await req('bobby','/servers/'+sid+'/choose-role','POST',{role_id:role.id});assert.equal((await req('bobby','/servers/'+sid+'/setup')).server.role_id,role.id);
  await req('alice','/servers/'+sid+'/roles/'+role.id+'/unlock','PATCH',{self_assignable:true,required_badge:'friend'});await req('bobby','/servers/'+sid+'/choose-role','POST',{role_id:role.id},403);await req('bobby','/badges/claim','POST',{badge_id:'friend'});await req('bobby','/servers/'+sid+'/choose-role','POST',{role_id:role.id});
  await req('alice','/servers/'+sid+'/roles','POST',{name:'Admin',permissions:['send','manage_roles']});const admin=(await req('alice','/servers/'+sid+'/setup')).roles.find((r:any)=>r.name==='Admin');await req('alice','/servers/'+sid+'/roles/'+admin.id+'/unlock','PATCH',{self_assignable:true,required_badge:null},400);await req('bobby','/servers/'+sid+'/choose-role','POST',{role_id:admin.id},403);
  const forum=await req('alice','/rooms','POST',{name:'Ideias',kind:'forum',server_id:sid});await req('alice','/rooms/'+forum.id+'/forum-tags','PATCH',{tags:['Jogos','Ajuda']});await req('bobby','/rooms/'+forum.id+'/forum-tags','PATCH',{tags:['hack']},403);await req('bobby','/rooms/'+forum.id+'/forum','POST',{title:'Primeiro',body:'Dicas',tags:['inexistente']},400);const topic=await req('bobby','/rooms/'+forum.id+'/forum','POST',{title:'Qual jogo?',body:'Vamos jogar juntos',tags:['Jogos']});await req('alice','/threads/'+topic.id+'/messages','POST',{body:'Vamos de aventura'});assert.equal((await req('alice','/rooms/'+forum.id+'/forum?tag=Jogos&q=jogo')).topics[0].replies,1);assert.equal((await req('alice','/rooms/'+forum.id+'/forum?tag=Ajuda')).topics.length,0);await req('carol','/rooms/'+forum.id+'/forum','GET',undefined,403);await req('bobby','/rooms/'+forum.id+'/messages','POST',{body:'Não deve sumir no fórum'},400);await req('bobby','/rooms/'+forum.id+'/polls','POST',{question:'X',options:['a','b'],hours:1},400);
  const count=async()=>Number((await db.query('SELECT count(*) AS n FROM notifications WHERE user_id=$1 AND room_id=$2',[bob.id,room.id]))[0].n);let n=await count();await req('alice','/rooms/'+room.id+'/messages','POST',{body:'Texto sem menção'});assert.equal(await count(),n);await req('bobby','/rooms/'+room.id+'/notifications','PATCH',{mode:'all'});const msg=await req('alice','/rooms/'+room.id+'/messages','POST',{body:'Texto para todos'});assert.equal(await count(),++n);await req('bobby','/rooms/'+room.id+'/notifications','PATCH',{mode:'mentions'});await req('alice','/rooms/'+room.id+'/messages','POST',{body:'Outro texto comum'});assert.equal(await count(),n);await req('alice','/rooms/'+room.id+'/messages','POST',{body:'Oi @bobby!'});assert.equal(await count(),++n);await req('bobby','/rooms/'+room.id+'/notifications','PATCH',{mode:'muted'});await req('alice','/rooms/'+room.id+'/messages','POST',{body:'Silenciado @bobby'});assert.equal(await count(),n);
  await db.query('UPDATE users SET sparks=1000 WHERE id=$1',[alice.id]);assert.equal((await req('alice','/shop')).items.length,12);await req('alice','/shop/gift','POST',{username:'carol',item_id:'aurora'},403);const before=(await req('alice','/shop')).sparks;await req('alice','/shop/gift','POST',{username:'bobby',item_id:'aurora'});assert.equal((await req('alice','/shop')).sparks,before-180);await req('alice','/shop/gift','POST',{username:'bobby',item_id:'aurora'},409);assert.equal((await req('alice','/shop')).sparks,before-180);await req('bobby','/shop/equip','POST',{item_id:'aurora',kind:'background'});await req('bobby','/shop/equip','POST',{item_id:'aurora',kind:'frame'},403);assert.equal((await req('bobby','/state')).me.equipped_background,'aurora');await req('alice','/shop/buy','POST',{item_id:'golden'});await req('alice','/shop/equip','POST',{item_id:'golden',kind:'color'});assert.equal((await req('bobby','/state')).users.find((u:any)=>u.id===alice.id).equipped_color,'golden');const beforeConcurrent=(await req('alice','/shop')).sparks;await Promise.all([1,2].map(()=>req('alice','/shop/gift','POST',{username:'bobby',item_id:'glow'},[200,409])));assert.equal((await req('alice','/shop')).sparks,beforeConcurrent-160);assert.equal(Number((await db.query('SELECT count(*) n FROM shop_gifts WHERE recipient_id=$1 AND item_id=$2',[bob.id,'glow']))[0].n),1);await req('alice','/blocks/'+bob.id,'POST');await req('alice','/shop/gift','POST',{username:'bobby',item_id:'glow'},403);await req('alice','/blocks/'+bob.id,'DELETE');
  await req('alice','/call-preferences/'+bob.id,'PUT',{volume:37});assert.equal((await req('alice','/call-preferences'))[0].volume,37);assert.equal((await req('bobby','/call-preferences')).length,0);await req('alice','/call-preferences/'+bob.id,'PUT',{volume:101},400);
  const starts_at=new Date(Date.now()+120000).toISOString(),event=await req('alice','/servers/'+sid+'/events','POST',{title:'Partida marcada',description:'Enquete e aviso',starts_at});await req('bobby','/events/'+event.id+'/poll','POST',{question:'Qual jogo?',options:['A','B']},403);await req('alice','/events/'+event.id+'/poll','POST',{question:'Qual jogo?',options:['A','B']});await req('carol','/events/'+event.id+'/poll/vote','POST',{choice:0},403);await req('bobby','/events/'+event.id+'/poll/vote','POST',{choice:0});await req('bobby','/events/'+event.id+'/poll/vote','POST',{choice:1});assert.deepEqual((await req('bobby','/events/'+event.id+'/extras')).poll.votes,[{choice:1,total:1}]);await req('bobby','/events/'+event.id+'/reminder','PUT',{minutes:5});await svc.tickReminders();await svc.tickReminders();assert.equal((await db.query("SELECT 1 FROM notifications WHERE user_id=$1 AND body LIKE 'Lembrete:%'",[bob.id])).length,1);await req('alice','/events/'+event.id+'/poll/close','POST');await req('bobby','/events/'+event.id+'/poll/vote','POST',{choice:0},409);
  await req('bobby','/servers/'+sid+'/transfer','POST',{target_id:alice.id,name:identity.name},403);await req('alice','/servers/'+sid+'/leave','POST',undefined,409);await req('alice','/servers/'+sid+'/transfer','POST',{target_id:carol.id,name:identity.name},400);await req('alice','/servers/'+sid+'/transfer','POST',{target_id:bob.id,name:'wrong'},400);await req('alice','/servers/'+sid+'/transfer','POST',{target_id:bob.id,name:identity.name});await req('carol','/servers/'+sid+'/transfer/respond','POST',{accept:true},403);await req('bobby','/servers/'+sid+'/transfer/respond','POST',{accept:true});assert.equal((await req('alice','/servers/'+sid+'/setup')).server.owner_id,bob.id);await req('alice','/servers/'+sid+'/settings','PATCH',identity,403);await req('bobby','/servers/'+sid+'/settings','PATCH',{...identity,bio:'Novo dono mantém imagens'});await req('alice','/servers/'+sid+'/leave','POST');await req('alice','/rooms/'+forum.id+'/forum','GET',undefined,403);
  // All new tables survive an encrypted backup; v0.6 content is accepted too.
  const password='a-long-backup-password',backup=await createBackup(db,path.join(dir,'uploads'),password);
  async function restore(bytes:Buffer,label:string){const pg=new PGlite(path.join(dir,label));const query=async(sql:string,p:any[]=[])=> (await pg.query(sql,p)).rows as any[];const target:any={query,exec:(s:string)=>pg.exec(s),transaction:(fn:any)=>pg.transaction(tx=>fn({query:async(s:string,p:any[]=[])=> (await tx.query(s,p)).rows})),close:()=>pg.close()};try{await migrate(target);await restoreBackup(target,path.join(dir,label+'-uploads'),password,bytes);assert.equal((await query('SELECT * FROM shop_items')).length,12);return await query('SELECT * FROM forum_topics');}finally{await pg.close();}}
  assert.equal((await restore(backup,'restored')).length,1);
  const dec=createDecipheriv('aes-256-gcm',scryptSync(password,backup.subarray(5,21),32),backup.subarray(21,33));dec.setAuthTag(backup.subarray(33,49));const legacy=JSON.parse(gunzipSync(Buffer.concat([dec.update(backup.subarray(49)),dec.final()])).toString());legacy.format='nexochat-6';for(const t of ['ownership_offers','shop_gifts','call_preferences','forum_topics','event_polls','event_poll_votes','event_reminders'])delete legacy.tables[t];legacy.tables.shop_items=legacy.tables.shop_items.filter((i:any)=>i.kind==='frame');legacy.tables.inventory=legacy.tables.inventory.filter((i:any)=>legacy.tables.shop_items.some((p:any)=>p.id===i.item_id));const salt=randomBytes(16),iv=randomBytes(12),enc=createCipheriv('aes-256-gcm',scryptSync(password,salt,32),iv),encrypted=Buffer.concat([enc.update(gzipSync(JSON.stringify(legacy))),enc.final()]);assert.equal((await restore(Buffer.concat([Buffer.from('NEXO6'),salt,iv,enc.getAuthTag(),encrypted]),'legacy')).length,0);
  await migrate(db);
 }finally{await svc.close();await rm(dir,{recursive:true,force:true});}
});
