import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {io as connect,type Socket} from 'socket.io-client';
test('enquetes, eventos, favoritos, mídia, canais privados, timeout e denúncias',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'nexo-community-'));process.env.DATA_DIR=dir;process.env.DATABASE_URL='';process.env.APP_ORIGIN='http://localhost:5173';
 const {openDb}=await import('../src/db.js'),{migrate}=await import('../src/migrate.js'),{createApp}=await import('../src/app.js');const db=await openDb();await migrate(db);const svc=createApp(db);await new Promise<void>(r=>svc.http.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+(svc.http.address() as any).port;const cookies:Record<string,string>={};let socket:Socket|undefined;
 async function req(w:string,p:string,method='GET',body?:any,status=200){const r=await fetch(base+'/api'+p,{method,headers:{Origin:process.env.APP_ORIGIN!,Cookie:cookies[w]||'',...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const cookie=r.headers.get('set-cookie');if(cookie)cookies[w]=cookie.split(';')[0];const data=await r.json();assert.equal(r.status,status,p+': '+JSON.stringify(data));return data;}
 const event=(name:string,data:any)=>new Promise<any>((resolve,reject)=>socket!.timeout(4000).emit(name,data,(e:any,r:any)=>e?reject(e):resolve(r)));
 try{
  for(const w of ['alice','bobby','carol'])await req(w,'/auth/register','POST',{username:w,password:'Strong-test-password-123'});
  const alice=(await req('alice','/state')).me,bob=(await req('bobby','/state')).me;
  await req('alice','/friends','POST',{username:'bobby'});await req('bobby','/friends/'+alice.id+'/accept','POST');const dm=await req('alice','/rooms','POST',{kind:'dm',name:'Polls',users:['bobby']});
  const poll=await req('alice','/rooms/'+dm.id+'/polls','POST',{question:'Qual jogo?',options:['Aventura','Corrida'],hours:1});
  await req('carol','/polls/'+poll.id+'/vote','POST',{choice:0},403);await req('bobby','/polls/'+poll.id+'/vote','POST',{choice:7},400);
  await Promise.all([0,1].map(choice=>req('bobby','/polls/'+poll.id+'/vote','POST',{choice})));let ex=await req('alice','/rooms/'+dm.id+'/extras');assert.equal(ex.polls[0].votes.reduce((n:number,v:any)=>n+v.total,0),1);
  await req('bobby','/polls/'+poll.id+'/vote','POST',{choice:null});assert.equal((await req('alice','/rooms/'+dm.id+'/extras')).polls[0].votes.length,0);
  await req('bobby','/polls/'+poll.id+'/close','POST',undefined,403);await req('alice','/polls/'+poll.id+'/close','POST');await req('bobby','/polls/'+poll.id+'/vote','POST',{choice:0},409);
  await req('bobby','/messages/'+poll.id+'/favorite','POST',{enabled:true});assert.equal((await req('bobby','/favorites')).length,1);assert.equal((await req('alice','/favorites')).length,0);
  await req('bobby','/messages/'+poll.id+'/pin','POST',{enabled:true},403);await req('alice','/messages/'+poll.id+'/pin','POST',{enabled:true});assert.equal((await req('bobby','/rooms/'+dm.id+'/extras')).pins.length,1);
  const server=await req('alice','/servers','POST',{name:'Turma'}),invite=await req('alice','/servers/'+server.id+'/invites','POST');await req('bobby','/invites/'+invite.code+'/join','POST');const channel=(await req('alice','/state')).rooms.find((r:any)=>r.server_id===server.id&&r.kind==='text');
  const starts_at=new Date(Date.now()+86400000).toISOString();const e=await req('bobby','/servers/'+server.id+'/events','POST',{title:'Partida',description:'Sábado juntos',starts_at});await req('carol','/events/'+e.id+'/rsvp','POST',{response:'going'},403);await req('alice','/events/'+e.id+'/rsvp','POST',{response:'going'});await req('alice','/events/'+e.id+'/rsvp','POST',{response:'maybe'});assert.equal((await req('bobby','/servers/'+server.id+'/hub')).events[0].attendees.length,1);
  await req('alice','/events/'+e.id,'PATCH',{title:'Partida',description:'Cancelada',starts_at,cancelled:true});await req('bobby','/events/'+e.id+'/rsvp','POST',{response:'going'},409);
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z4Z8AAAAASUVORK5CYII=','base64');const upload=async(room?:string)=>{const f=new FormData();f.append('file',new Blob([png],{type:'image/png'}),'test.png');return req('alice','/upload'+(room?'?room='+room:''),'POST',f);};const assetFile=await upload();
  await req('bobby','/servers/'+server.id+'/assets','POST',{name:'own',kind:'emoji',attachment_id:assetFile.id},403);await req('alice','/servers/'+server.id+'/assets','POST',{name:'ola',kind:'emoji',attachment_id:assetFile.id});const sticker=await req('alice','/servers/'+server.id+'/assets','POST',{name:'gato',kind:'sticker',attachment_id:assetFile.id});
  assert.equal((await fetch(base+'/api/files/'+assetFile.id,{headers:{Cookie:cookies.bobby}})).status,200);assert.equal((await fetch(base+'/api/files/'+assetFile.id,{headers:{Cookie:cookies.carol}})).status,403);
  await req('bobby','/rooms/'+channel.id+'/messages','POST',{body:'',sticker_id:sticker.id});await req('bobby','/rooms/'+dm.id+'/messages','POST',{body:'',sticker_id:sticker.id},400);
  const m=await req('alice','/rooms/'+channel.id+'/messages','POST',{body:'Mensagem moderada'});await req('bobby','/messages/'+m.id+'/report','POST',{reason:'Teste de denúncia'});await req('bobby','/messages/'+m.id+'/report','POST',{reason:'Segunda tentativa'});await req('bobby','/servers/'+server.id+'/reports','GET',undefined,403);const reports=await req('alice','/servers/'+server.id+'/reports');assert.equal(reports.length,1);await req('alice','/reports/'+reports[0].id,'PATCH',{status:'resolved'});
  const file=await upload(channel.id);const fileMsg=await req('alice','/rooms/'+channel.id+'/messages','POST',{body:'Arquivo privado',attachment_id:file.id});await req('bobby','/messages/'+fileMsg.id+'/favorite','POST',{enabled:true});
  await req('alice','/servers/'+server.id+'/roles','POST',{name:'VIP',permissions:['send']});const role=(await req('alice','/servers/'+server.id+'/manage')).roles[0];await req('alice','/servers/'+server.id+'/members/'+bob.id,'PATCH',{action:'role',role_id:role.id});
  socket=connect(base,{transports:['websocket'],extraHeaders:{Cookie:cookies.bobby,Origin:process.env.APP_ORIGIN!},reconnection:false});await new Promise<void>((resolve,reject)=>{socket!.once('connect',resolve);socket!.once('connect_error',reject);});assert.equal((await event('call-join',{room:channel.id})).ok,true);
  await req('alice','/rooms/'+channel.id+'/permissions','PATCH',{private:true,roles:[role.id],slow_seconds:60});assert.ok((await req('bobby','/state')).rooms.some((r:any)=>r.id===channel.id));
  await req('bobby','/rooms/'+channel.id+'/messages','POST',{body:'Mensagem nova no modo lento'},429);
  await req('alice','/servers/'+server.id+'/members/'+bob.id,'PATCH',{action:'role',role_id:null});assert.ok(!(await req('bobby','/state')).rooms.some((r:any)=>r.id===channel.id));await req('bobby','/rooms/'+channel.id+'/messages','GET',undefined,403);assert.equal((await event('call-join',{room:channel.id})).ok,false);assert.equal((await fetch(base+'/api/files/'+file.id,{headers:{Cookie:cookies.bobby}})).status,403);assert.ok(!(await req('bobby','/favorites')).some((m:any)=>m.id===fileMsg.id));
  await req('alice','/rooms/'+channel.id+'/permissions','PATCH',{private:false,roles:[],slow_seconds:0});await req('alice','/servers/'+server.id+'/timeout/'+bob.id,'POST',{minutes:10});await req('bobby','/rooms/'+channel.id+'/messages','POST',{body:'Não pode enviar'},403);assert.equal((await event('call-join',{room:channel.id})).ok,false);await req('bobby','/rooms/'+channel.id+'/messages');await req('alice','/servers/'+server.id+'/timeout/'+bob.id,'POST',{minutes:0});await req('bobby','/rooms/'+channel.id+'/messages','POST',{body:'Voltei'});await req('bobby','/rooms/'+channel.id+'/messages','POST',{body:'Voltei'},429);
  await req('alice','/profile','PATCH',{...(await req('alice','/state')).me,theme:'forest',name_color:'#8bd4b1',banner_style:'dots'});await migrate(db);assert.equal((await req('alice','/state')).me.theme,'forest');assert.equal((await req('bobby','/state')).users.find((u:any)=>u.id===alice.id).banner_style,'dots');
  await req('bobby','/servers/'+server.id,'DELETE',{name:'Turma'},403);
  await req('alice','/servers/'+server.id,'DELETE',{name:'Nome incorreto'},400);
  const ownerOnlyRole=await req('alice','/servers/'+server.id+'/roles','POST',{name:'Administrador',permissions:['manage_channels','manage_members','manage_messages','manage_roles','invite','send']});
  const adminRole=(await req('alice','/servers/'+server.id+'/manage')).roles.find((r:any)=>r.name==='Administrador');await req('alice','/servers/'+server.id+'/members/'+bob.id,'PATCH',{action:'role',role_id:adminRole.id});
  await req('bobby','/servers/'+server.id,'DELETE',{name:'Turma'},403);assert.equal((await event('call-join',{room:channel.id})).ok,true);
  const ended=new Promise<void>(resolve=>socket!.once('call-ended',()=>resolve()));await req('alice','/servers/'+server.id,'DELETE',{name:'Turma'});await ended;
  assert.equal((await req('alice','/state')).servers.some((s:any)=>s.id===server.id),false);assert.equal((await req('bobby','/state')).rooms.some((r:any)=>r.server_id===server.id),false);await req('bobby','/rooms/'+channel.id+'/messages','GET',undefined,404);assert.equal((await db.query('SELECT id FROM attachments WHERE id=$1',[file.id])).length,0);
  console.log('PASS: todos os recursos 0.5 e controles de acesso exercitados.');
 }finally{socket?.disconnect();await svc.close();await rm(dir,{recursive:true,force:true});}
});
