import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import * as OTPAuth from 'otpauth';
import {PGlite} from '@electric-sql/pglite';
test('0.6: recuperação, TOTP, busca, tópicos, agendamento, perfil, missões e backup',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'nexo-six-'));process.env.DATA_DIR=dir;process.env.DATABASE_URL='';process.env.APP_ORIGIN='http://localhost:5173';const {openDb}=await import('../src/db.js'),{migrate}=await import('../src/migrate.js'),{createApp}=await import('../src/app.js'),{createBackup,restoreBackup}=await import('../src/backup.js');const db=await openDb();await migrate(db);const svc=createApp(db);await new Promise<void>(r=>svc.http.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+(svc.http.address() as any).port;const cookies:Record<string,string>={};const password='Strong-test-password-123';
 async function req(w:string,p:string,method='GET',body?:any,status=200){const r=await fetch(base+'/api'+p,{method,headers:{Origin:process.env.APP_ORIGIN!,Cookie:cookies[w]||'',...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const cookie=r.headers.get('set-cookie');if(cookie)cookies[w]=cookie.split(';')[0];const data=await r.json();assert.equal(r.status,status,p+': '+JSON.stringify(data));return data;}
 try{
  for(const name of ['alice','bobby','carol'])await req(name,'/auth/register','POST',{username:name,password});const alice=(await req('alice','/state')).me;
  const rc=await req('alice','/security/recovery','POST',{password});assert.equal(rc.codes.length,8);assert.equal((await req('alice','/security')).recovery_remaining,8);await req('alice','/security/setup','POST',{password:'wrong-password'},401);
  const setup=await req('alice','/security/setup','POST',{password});const t=new OTPAuth.TOTP({secret:OTPAuth.Secret.fromBase32(setup.secret)});const activated=await req('alice','/security/confirm','POST',{password,otp:t.generate()});assert.equal((await req('alice','/security')).enabled,true);
  await req('guest','/auth/login','POST',{username:'alice',password},401);await req('guest','/auth/login','POST',{username:'alice',password,otp:t.generate()},401);
  await db.query('UPDATE account_security SET last_counter=-1 WHERE user_id=$1',[alice.id]);const loginToken=t.generate();await req('guest','/auth/login','POST',{username:'alice',password,otp:loginToken});await req('guest','/auth/login','POST',{username:'alice',password,otp:loginToken},401);
  await req('guest','/auth/login','POST',{username:'alice',password,otp:activated.codes[0]});await req('guest','/auth/login','POST',{username:'alice',password,otp:activated.codes[0]},401);
  const newPassword='New-test-password-456';await req('guest','/auth/recover','POST',{username:'alice',code:rc.codes[0],password:newPassword},401);await req('guest','/auth/recover','POST',{username:'alice',code:activated.codes[1],password:newPassword});await req('alice','/state','GET',undefined,401);await req('guest','/auth/recover','POST',{username:'alice',code:activated.codes[1],password:newPassword},401);await req('alice','/auth/login','POST',{username:'alice',password:newPassword});assert.equal((await req('alice','/security')).enabled,false);
  await req('alice','/friends','POST',{username:'bobby'});await req('bobby','/friends/'+alice.id+'/accept','POST');const room=await req('alice','/rooms','POST',{kind:'dm',name:'Histórico',users:['bobby']});const root=await req('alice','/rooms/'+room.id+'/messages','POST',{body:'Uma conversa pesquisável'});
  await req('alice','/messages/'+root.id+'/thread','POST',{title:'Nosso tópico'});await req('bobby','/threads/'+root.id+'/messages','POST',{body:'Resposta dentro do tópico'});assert.equal((await req('alice','/threads/'+root.id)).messages.length,1);assert.equal((await req('alice','/rooms/'+room.id+'/messages')).messages.length,1);await req('carol','/threads/'+root.id,'GET',undefined,403);await req('alice','/threads/'+root.id,'PATCH',{closed:true});await req('bobby','/threads/'+root.id+'/messages','POST',{body:'Outro texto'},409);
  assert.equal((await req('alice','/search?q=pesquisável')).messages.length,1);assert.equal((await req('carol','/search?q=pesquisável')).messages.length,0);assert.equal((await req('alice','/search?person=bobby')).messages[0].thread_id,root.id);
  const scheduled=await req('alice','/rooms/'+room.id+'/scheduled','POST',{body:'Texto no futuro',send_at:new Date(Date.now()+60000).toISOString()});await db.query('UPDATE scheduled_messages SET send_at=now() WHERE id=$1',[scheduled.id]);await Promise.all([svc.tickScheduled(),svc.tickScheduled()]);assert.equal((await db.query('SELECT id FROM messages WHERE id=$1',[scheduled.id])).length,1);assert.equal((await req('alice','/scheduled'))[0].status,'sent');
  const canceled=await req('alice','/rooms/'+room.id+'/scheduled','POST',{body:'Cancelar isto',send_at:new Date(Date.now()+60000).toISOString()});await req('bobby','/scheduled/'+canceled.id,'DELETE',undefined,409);await req('alice','/scheduled/'+canceled.id,'DELETE');
  const form=new FormData();form.append('file',new Blob([new Uint8Array([26,69,223,163,0,1,2])],{type:'audio/webm'}),'voice.webm');const audio=await req('alice','/upload?room='+room.id+'&voice=true','POST',form);assert.equal(audio.mime,'audio/webm');await req('alice','/rooms/'+room.id+'/messages','POST',{body:'',attachment_id:audio.id});const fileResponse=await fetch(base+'/api/files/'+audio.id,{headers:{Cookie:cookies.bobby}});assert.equal(fileResponse.headers.get('content-type'),'audio/webm');assert.equal(fileResponse.headers.get('content-disposition'),null);
  const server=await req('alice','/servers','POST',{name:'Perfil local'});const inv=await req('alice','/servers/'+server.id+'/invites','POST');assert.equal((await req('bobby','/invites/'+inv.code)).name,'Perfil local');await req('bobby','/invites/'+inv.code+'/join','POST');await req('bobby','/servers/'+server.id+'/profile','PATCH',{nickname:'Apelido',bio:'Bio local',avatar_id:null});assert.equal((await req('alice','/state')).community_profiles.find((p:any)=>p.nickname==='Apelido').bio,'Bio local');await req('carol','/servers/'+server.id+'/profile','GET',undefined,403);
  await req('alice','/accessibility','PATCH',{font_size:20,contrast:true,reduce_motion:true});assert.equal((await req('alice','/state')).me.accessibility.font_size,20);await req('alice','/accessibility','PATCH',{font_size:200,contrast:true,reduce_motion:true},400);
  await req('alice','/messages/'+root.id+'/favorite','POST',{enabled:true});const q=await req('alice','/quests');assert.equal(q.quests.find((q:any)=>q.id==='saved').progress,1);await req('alice','/quests/saved/claim','POST');await req('alice','/quests/saved/claim','POST',undefined,409);
  const failSend=await req('alice','/rooms/'+room.id+'/scheduled','POST',{body:'Não enviar bloqueado',send_at:new Date(Date.now()+60000).toISOString()});await req('alice','/blocks/'+(await req('bobby','/state')).me.id,'POST');await db.query('UPDATE scheduled_messages SET send_at=now() WHERE id=$1',[failSend.id]);await svc.tickScheduled();assert.equal((await db.query('SELECT status FROM scheduled_messages WHERE id=$1',[failSend.id]))[0].status,'failed');assert.equal((await req('bobby','/search?q=pesquisável')).messages.length,0);
  const encrypted=await createBackup(db,path.join(dir,'uploads'),'backup-password-12345');assert.equal(encrypted.includes(Buffer.from('pesquisável')),false);await assert.rejects(()=>restoreBackup(db,path.join(dir,'restore'),'wrong-password',encrypted));
  const client=new PGlite();const restored:any={query:async(sql:string,args:any[]=[])=> (await client.query(sql,args)).rows,exec:(sql:string)=>client.exec(sql),transaction:(fn:any)=>client.transaction(tx=>fn({query:async(sql:string,args:any[]=[])=> (await tx.query(sql,args)).rows}))};try{await migrate(restored);await restoreBackup(restored,path.join(dir,'restored'),'backup-password-12345',encrypted);assert.equal((await restored.query('SELECT count(*)::int AS n FROM users'))[0].n,3);assert.equal((await restored.query('SELECT count(*)::int AS n FROM sessions'))[0].n,0);assert.equal((await restored.query('SELECT thread_id FROM messages WHERE thread_id IS NOT NULL'))[0].thread_id,root.id);assert.deepEqual(await readFile(path.join(dir,'restored',audio.id)),await readFile(path.join(dir,'uploads',audio.id)));await assert.rejects(()=>restoreBackup(restored,path.join(dir,'again'),'backup-password-12345',encrypted),/vazio/);}finally{await client.close();}
 }finally{await svc.close();await rm(dir,{recursive:true,force:true});}
});
